### ISSUE TITLE
CISv2 - There is no profile name in the ClusterScan CR when no value for scanProfileName is given

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#10]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- On an EKS cluster, run CIS v2 scan by deploying a ClusterScan CR with "scanProfileName" = ""
- Scan is run and the report is generated.
- But the report CR or the ClusterScan CR does not show which scan profile it has run. (View in YAML)

**Expected Result:**
There should be some field in the report CR or the ClusterScan CR to indicate which profile was run which can be displayed on the UI (easier for user to udnerstand which scan has run )

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `8d9cedde931`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): EKS
- Kubernetes version (use `kubectl version`):

```
1.17
```

**Comment by prachidamle** [comment]
This issue has been fixed and available to test via the new tag:    
- repository: rancher/cis-operator
- tag: v0.0.4
- The rancher-cis-benchmark chart has been updated to use this tag. https://github.com/rancher/charts/pull/586


Fix provided:
- A new field 'status.lastRunScanProfileName' has been added to the ClusterScan CRD. This will be updated in the status of the  clusterscan after the scan runs. Few additional printer columns have been added to the ClusterScan CRD which will display this field in the kubectl output.

Example: Here is how the clusterscan fields will be displayed that shows the CLUSTERSCANPROFILE used
`
$ kubectl --kubeconfig ~/.kube/test_config_master  get clusterscans 

NAME           STATUS   CLUSTERSCANPROFILE       TOTAL   PASS   FAIL   SKIP   NOT APPLICABLE   LASTRUNTIMESTAMP
rke-cis               fail        rke-profile-hardened               92      59         13      0       20                            2020-09-05T01:18:28Z
rke-cis-perm    pass     rke-profile-permissive             92       58         0       0       34                            2020-09-05T01:19:36Z
run-eks-1.0       error                                                                           

`

**Comment by prachidamle** [comment]
Marking this as Review as the CIS v2 chart is still under review. 
But can be tested using helm cli:
```
$ helm install clusterscan-operator ./rancher-cis-benchmark/charts/ --create-namespace=true -n cis-operator-system --kubeconfig ~/.kube/test_config_master 
```

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `3ca11da829 `**

- Deploy cis-operator from repo - https://github.com/prachidamle/charts.git branch: cis-v2-chart. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- Deployed an RKE cluster cluster. Run a scan with `scanProfileName: ""`
- When the scan has finished, and status of the scan is `Pass`, the scan CR has `lastRunScanProfileName: rke-profile-permissive`
