### ISSUE TITLE
RKE2 Recommended Tolerations Fail to Scan

### ISSUE THREAD

**Issue by JamesB41** [rancher/cis-operator#102]
The recommendation for RKE2 deployments (found here: https://docs.rke2.io/install/ha/#2a-optional-consider-server-node-taints) is to taint Server nodes with CriticalAddonsOnly=true:NoExecute. As a result, the CIS Operator appears to not properly scan server nodes. When modifying this manually in a cluster I have deployed, the operator appears to work properly.

PR here: https://github.com/rancher/cis-operator/pull/101

**Comment by dhruvmewada15** [comment]
Issue Duplicate/Similar to: https://github.com/rancher/rancher/issues/37129
PR merged: https://github.com/rancher/cis-operator/pull/101
Hence Closing.
