### ISSUE TITLE
Allow configuring imagePullPolicy

### ISSUE THREAD

**Issue by tallaxes** [rancher/cis-operator#105]
The ability to customize `imagePullPolicy` is important in some use cases, including in airgapped environments and/or with container images pre-loaded on nodes. In cis-operator `imagePullPolicy` is currently hard-coded to `Always` in
- https://github.com/rancher/cis-operator/blob/d345139a91c4e82eba89adc2ffa7a2ba986477b4/pkg/securityscan/job/job.go#L165
- https://github.com/rancher/cis-operator/blob/d345139a91c4e82eba89adc2ffa7a2ba986477b4/pkg/securityscan/core/templates/pluginConfig.template#L89

**Comment by doflamingo721** [comment]
The `imagePullPolicy` for cis-benchmark has been changed to `IfNotPresent` as part of https://github.com/rancher/rancher/issues/39673 issue. The chart will now pull from the pre-loaded images if present rather than the registry.

**Comment by mitulshah-suse** [comment]
> The `imagePullPolicy` for cis-benchmark has been changed to `IfNotPresent` as part of [rancher/rancher#39673](https://github.com/rancher/rancher/issues/39673) issue. The chart will now pull from the pre-loaded images if present rather than the registry.

@tallaxes Please advise if this is still relevant after the above update.

**Comment by tallaxes** [comment]
@mitulshah-suse Yes, fixed by https://github.com/rancher/cis-operator/pull/171
