### ISSUE TITLE
Cluster scans fail when the cluster has nodes with individual roles.

### ISSUE THREAD

**Issue by dereknola** [rancher/cis-operator#107]
**On Rancher 2.6-head commit id: `b8a44fa`**

With 1 etcd, 1 control and 1 worker node AWS EC2 rke2
<img alt="Screen Shot 2021-08-23 at 4 55 40 PM" width="1679" src="https://user-images.githubusercontent.com/26032343/130534205-b3f38892-15d8-4a74-8ff9-e36738d07b29.png">

With 1 node, all roles AWS EC2 rke2, permissive scan passes
<img alt="Screen Shot 2021-08-23 at 5 00 35 PM" width="1654" src="https://user-images.githubusercontent.com/26032343/130534520-a2fe6ad4-b7f5-47e6-bf3c-ac1c47e32bdc.png">

The root cause is that the cis-operator makes no distinction between nodes when performing the scan. So a `control-plane`
only node will still be scanned for the `etcd` checks. These checks will fail incorrectly as the files or flags do not exist, resulting in neither an explicit pass nor fail. Instead the result becomes "mixed" but does not tell the user which node failed the check.

Take for example check 1.1.1:
![image](https://user-images.githubusercontent.com/11727736/133685031-32072f49-6818-410d-b15b-0a44bfb0b542.png)
This check should only be run on nodes with the `control-plane` role. Here, the test fails on two of the nodes, the etcd and worker, because that file does not exist. However, the UI does not inform the user that these two nodes failed because they did not explicitly fail the check (the file wasn't 777, it was N/A).

**Comment by sowmyav27** [comment]
Same issue is seen when a k3s cluster is deployed from rancher on 2.6-head commit id: `ba43472`

**Comment by WolfspiritM** [comment]
This caused me headache aswell. I have 3 masters and 3 workers and the cis benchmark always failed on the fresh cluster.

Can this be related to https://github.com/rancher/cis-operator/pull/101 which just prevents the scan from running on masters at all?

**Comment by JamesB41** [comment]
@WolfspiritM Removing the server node taints caused the same behavior you mention, which I was trying to solve with #101 . Anything that required scanning on the master nodes as well would show up as "Mixed" and when you expanded the individual tasks, you wouldn't see the actual nodes listed. Once we removed the taints (as a temporary test), all the Mixed ones went away. As far as the file permission issues, I seem to recall that we couldn't get "Warns" to go away on some file permissions...even though they were 100% right.

**Comment by mitulshah-suse** [comment]
This issue should be resolved already with the https://github.com/rancher/cis-operator/pull/101 
Moving to test to verify.
