### ISSUE TITLE
After installing CISv2 on a hardened cluster, tests fail on running a hardened cis 1.5 rke scan

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#11]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy a CIS 1.5 hardened cluster (all the necessary manual steps for hardening should be done)
- Install CIS v2 app on the cluster
- RUn a `rke-profile-hardened` scan on the cluster by creating a clusterScan
- There are 2 failures in the run. - tests 5.1.5 or 5.3.2 fail
- Run the manual steps of hardening on the cluster - related to namespaces.
- RUn a `rke-profile-hardened` scan again
- There are no failures.

**Expected Result:**
CIS scan hardened run on a hardened cluster (before installing the app) should result in no failures.

Question: Is this something we have to document ? 

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `8d9cedde93 `
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom - 8 nodes - 3 etcd, 2 control and 3 worker nodes
- Kubernetes version (use `kubectl version`):

```
1.18
```

**Comment by prachidamle** [comment]
Adding in following fixes while installing the rancher-cis-benchmark chart:
a) Added a post-install hook that patches the default serviceaccount of cis-operator-system namespace to add flag automountServiceAccountToken: false. This is needed to pass cis 1.5 test 5.1.5 that breaks after creating the new cis-operator-system namespace as part of chart install.
b) Apply a basic network policy to the cis-operator-system namespace that is needed to pass cis-1.5 test 5.3.2

**Comment by prachidamle** [comment]
https://github.com/rancher/charts/pull/664

**Comment by sowmyav27** [comment]
**On master-head - commit id: `8fd81a9b4`**

- CIS benchmark chart image
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.6
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.0
  sonobuoy:
    repository: rancher/sonobuoy-sonobuoy
    tag: v0.16.3
```
- two tests fail when a hardened scan is run on a CIS 1.5 hardened cluster. - tests - `5.1.5` and `5.3.2` fail

Reopening the issue

**Comment by sowmyav27** [comment]
Logged issue for tests 5.1.5 and 5.3.2 failing here - https://github.com/rancher/fleet/issues/94 and https://github.com/rancher/rancher/issues/29014

**Comment by maggieliu** [comment]
Fleet needs to pass the CIS scan because it's auto deployed in 2.5. For the other charts it will be post 2.5.

**Comment by deniseschannon** [comment]
Note: CIS hardened cluster will only work for downstream clusters for 2.5.

**Comment by prachidamle** [comment]
So for Test 5.1.5, following are the namespaces for which the default service accounts do not have the automount flag false, causing it to fail:

- "dashboard-shells"
- "default"
- "fleet-system"
- "kube-system"


And for Test 5.3.2, following are the namespaces which do not have any network policy defined:
- cattle-system

**Comment by sowmyav27** [comment]
**On latest master-head - commit id: `0ccce450`**

- Deploy a CIS 1.5 hardened cluster.
- Test 5.1.5 fails. 
- Script `kubectl get serviceaccounts --all-namespaces -o json | jq -r '.items[] | select(.metadata.name=="default") | select((.automountServiceAccountToken == null) or (.automountServiceAccountToken == true))' | jq .metadata.namespace` lists namespace `fleet-system`

**Comment by sowmyav27** [comment]
**On master-head - commit id:`2229f5cd7`**

- Deploy a CIS 1.5 hardened cluster. (verified both 1.19.2 and 1.18.9 k8s clusters)
- Test 5.1.5 fails.
- `"fleet-system"` fails and is resulted in the below script when run

```
kubectl get serviceaccounts --all-namespaces -o json | jq -r '.items[] | select(.metadata.name=="default") | select((.automountServiceAccountToken == null) or (.automountServiceAccountToken == true))' | jq .metadata.namespace
```
Reopening the issue

**Comment by prachidamle** [comment]
The reason is that the fleet-agent chart generated, has wrong image tag for the kubectl image the post-install hook uses.

https://github.com/rancher/fleet/issues/94

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f7878`**

- Deploy a cis 1.5 hardened cluster. 
- Run rke-profile-hardened scan on the cluster
- No failures are seen

<img width="1411" alt="Screen Shot 2020-09-27 at 3 29 10 PM" src="https://user-images.githubusercontent.com/26032343/94377458-9f448000-00d6-11eb-91a9-e23e7709a332.png">
