### ISSUE TITLE
RKE 2 Rancher 2.6.2 CIS 1.6 Benchmarks failing with false alarms

### ISSUE THREAD

**Issue by szalayg** [rancher/cis-operator#111]
When running CIS 1.6 Benchmarks on an RKE2-based cluster (Rancher 2.6.2) we are getting false positive alerts, like:

**State:** warn
**Node:** node
**Desc:** Ensure that the --kubeconfig kubelet.conf file ownership is set to root:root (Manual)
**Remediation:** Run the below command (based on the file location on your system) on the each worker node.
For example,
chown root:root /var/lib/rancher/rke2/agent/kubelet.kubeconfig

**Audit:** /bin/sh -c 'if test -e /var/lib/rancher/rke2/agent/kubelet.kubeconfig; then stat -c %U:%G /var/lib/rancher/rke2/agent/kubelet.kubeconfig; fi' 

**State:** warn
**Node:** node
**Desc:** Ensure that the certificate authorities file permissions are set to 644 or more restrictive (Manual)
**Remediation:** Run the following command to modify the file permissions of the
--client-ca-file chmod 644 <filename>

**Audit:** stat -c %a /var/lib/rancher/rke2/server/tls/server-ca.crt

**State:** warn
**Node:** node
**Desc:** Ensure that the client certificate authorities file ownership is set to root:root (Manual)
**Remediation:** Run the following command to modify the ownership of the --client-ca-file.
chown root:root <filename>

**Audit:** /bin/sh -c 'if test -e /var/lib/rancher/rke2/agent/client-ca.crt; then stat -c %U:%G /var/lib/rancher/rke2/agent/client-ca.crt; fi' 

All the affected servers have been adjusted as suggested, but the checks do not recognize the changes. Please have a look.

**Comment by rayandas** [comment]
Validated on Rancher v2.6.9 with Kubernetes version `v1.24.8+rke2r1`. The errors are not reproducible, it has been fixed. Hence closing the ticket.
