### ISSUE TITLE
CISv2 scans stuck in "In-Progress" state when an invalid scanProfileName is given

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#13]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Repo: `https://github.com/prachidamle/charts.git` branch: `civ-v2-chart`
- Run a scan on a cluster - "scanProfileName: strke-profile-permissiveing" (something invalid)
- Error in cis-operator logs: `time="2020-08-31T19:41:42Z" level=error msg="Error validating ClusterScanProfile strke-profile-permissiveing, error: clusterscanprofiles.cis.cattle.io \"strke-profile-permissiveing\" not found"`
- CIS scans stuck in "In-Progress" state in Dashboard UI under "ClusterScans"

**Expected Result:**
- An error should be seen on the dashboard UI stating that the clusterprofile is incorrect/invalid

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `8d9cedd` - 3 etcd, 2 control and 3 worker nodes.
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom 8 nodes
- Kubernetes version (use `kubectl version`):

```
1.18
```

**Comment by prachidamle** [comment]
This issue has been fixed and available to test via the new tag:    
- repository: rancher/cis-operator
- tag: v0.0.4
- The rancher-cis-benchmark chart has been updated to use this tag. https://github.com/rancher/charts/pull/586


Fix provided:
- A new `status.display.state` field has been added to the ClusterScan CRD and this will contain the state of the ClusterScan: pass/fail/error/reporting.
This state will be displayed under STATUS column of the kubectl get output.

Example: Here is how the clusterscan fields will be displayed that shows the the STATUS field to reflect the state of the scan as (pass/fail/error/reporting)

```
$ kubectl --kubeconfig ~/.kube/test_config_master  get clusterscans 

NAME           STATUS   CLUSTERSCANPROFILE       TOTAL   PASS   FAIL   SKIP   NOT APPLICABLE   LASTRUNTIMESTAMP
rke-cis        fail     rke-profile-hardened     92      59     13     0      20               2020-09-05T01:18:28Z
rke-cis-perm   pass     rke-profile-permissive   92      58     0      0      34               2020-09-05T01:19:36Z
run-eks-1.0    error 

```
If an invalid scanProfileName is given, the scan will be in "error" state

**Comment by sowmyav27** [comment]
**On master-head - commit id: `3ca11da829 `**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- Create a ClusterScan CR and give in invalid value of scanProfileName
- Scan is seen in `Error` state.
` The reason why it failed i.e. `message` field of the scan CR is `blank` - has no value. Issue logged to track this - https://github.com/rancher/cis-operator/issues/22
