### ISSUE TITLE
CIS 1.20 benchmark support

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#135]
We currently have scan profiles for CIS 1.5 (k8s 1.5) and CIS 1.6 (k8s 1.16-1.18). New CIS 1.20 Benchmark has been published that supports k8s 1.19-1.20.

Also kube-bench has a profile for it - https://github.com/aquasecurity/kube-bench/tree/main/cfg/cis-1.20

We should look into updating rancher's CIS scan profiles to support CIS 1.20 benchmarks. 

cc @macedogm thanks for bringing up this request.

**Comment by macedogm** [comment]
SURE-3988

**Comment by macedogm** [comment]
FYI CIS released [Kubernetes V1.23 benchmark](https://workbench.cisecurity.org/benchmarks/7532) on Jan 1st. There is not yet a related kube-bench release.

**Comment by macedogm** [comment]
> FYI CIS released [Kubernetes V1.23 benchmark](https://workbench.cisecurity.org/benchmarks/7532) on Jan 1st. There is not yet a related kube-bench release.

Looks like CIS v1.23 is already available in [kube-bench](https://github.com/aquasecurity/kube-bench/tree/main/cfg/cis-1.23).

**Comment by dhruvmewada15** [comment]
Validation Steps:

1. Deploy a Rancher Server
2. Create a 4 downstream cluster of following configurations:
         -     Single node non-hardened cluster
         -     Single node hardened cluster
         -     Multi node non-hardened cluster (Each node with distinct roles i.e 1 cp, 1 etcd, 1 worker)
         -     Multi node hardened cluster (Each node with distinct roles i.e 1 cp, 1 etcd, 1 worker)
3. Install rancher-cis-benchmark:v2.0.5-rc4 in each of the cluster.
4. Run CIS scans of cis-1.20 profiles and observe the results.

Expected Result:
All scans should pass

**Comment by rayandas** [comment]
Got `1.2.18` check failure for 1.6 and 1.20 K3s hardened multinode cluster. Reopening this issue to fix that failure.

**Comment by rishabhmsra** [comment]
Re-opening this issue:

Validated on rancher v2.6.7-rc3

- Provisioned k8s v1.24, downstream RKE1, RKE2, K3s clusters with below configurations:
  - Single node non-hardened cluster
  - Single node hardened cluster
  - Multi node non-hardened cluster (Each node with distinct roles i.e 1 cp, 1 etcd, 1 worker)
  - Multi node hardened cluster (Each node with distinct roles i.e 1 cp, 1 etcd, 1 worker)
- Installed CIS benchmark 2.0.5-rc5 chart and ran the cis-1.20 permissive and hardened profile scans on all the downstream clusters. There were failures in the scans, provided the details to @rayandas.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6.7-rc3

Steps followed:
- Provisioned k8s v1.24, downstream RKE1, RKE2, K3s clusters with below configurations:
  - Single node non-hardened cluster
  - Single node hardened cluster
  - Multi node non-hardened cluster (Each node with distinct roles i.e 1 cp, 1 etcd, 1 worker)
  - Multi node hardened cluster (Each node with distinct roles i.e 1 cp, 1 etcd, 1 worker)
- Installed CIS benchmark 2.0.5-rc6 and ran the scans with cis-1.20 profiles, all the scans passed.

Result:
- All the scans passed successfully, hence closing the issue.
- RKE1 - single node:
![RKE1-sn](https://user-images.githubusercontent.com/36376154/180775534-48fc72c2-843c-4b9a-84fd-fd5fbbc25625.png)

- RKE1 - multinode:
![rke1-mn](https://user-images.githubusercontent.com/36376154/180775689-ec04b147-d7b0-4139-8d7a-0b1829a5d20d.png)

- RKE1 - hardened single node:
![RKE1-sn-hardened](https://user-images.githubusercontent.com/36376154/180776236-6b9de88a-4d12-4cff-a8c5-98ba570c00a3.png)

- RKE1 - hardened multinode:
![rke1-hardened-mn](https://user-images.githubusercontent.com/36376154/180776408-4c4c49d8-2143-4b4c-98f8-957c90c7734f.png)

- RKE2 - single node:
![rke2-sn](https://user-images.githubusercontent.com/36376154/180776558-f98beeed-9be9-4337-b023-02a15ab20fa0.png)

- RKE2 - multinode:
![rke2-multinode](https://user-images.githubusercontent.com/36376154/180776635-89d1c595-116d-4a0a-87bf-d754b51de999.png)

- RKE2 - hardened single node:
![rke2-hardened-sn](https://user-images.githubusercontent.com/36376154/180776760-7c84c7ae-4b88-4dae-bec4-32ae94cdd315.png)

- RKE2 - hardened multinode:
![rke2-hardened-mn](https://user-images.githubusercontent.com/36376154/180776861-a07e332b-ec23-404a-83c2-5dc72b334691.png)

- K3s - hardened:
![k3s-hardened1](https://user-images.githubusercontent.com/36376154/180777870-f964878b-537a-42bc-b30c-168592b99081.png)

- K3s - single node
![k3s-sn](https://user-images.githubusercontent.com/36376154/180778162-fc59d2f5-e967-4c39-85bf-6c1b1a6e0fd4.png)

- K3s - multinode
![k3s - multinode](https://user-images.githubusercontent.com/36376154/180778694-33044be3-6e0d-4534-8c20-c219d2576dc7.png)
