### ISSUE TITLE
Scan process didn’t verify that the permissions are 644, correctly

### ISSUE THREAD

**Issue by bguzman-3pillar** [rancher/cis-operator#137]
Validating the scan process on:
- Importing a k3s HA cluster (3 server, 1 agent) with this version `v1.20.15+k3s1`, upgraded to `v1.21.9+k3s1` using Rancher UI.
- Add the CIS Benchmark (2.0.2) app and run the scan 
- Kubernetes version: `v1.21.9+k3s1`

Scan result gave those errors:

![image](https://user-images.githubusercontent.com/95362932/152234204-630eda7d-39c8-4af4-aae0-4b715be6a9fa.png)
The worker node failed.

This check: https://rancher.com/docs/k3s/latest/en/security/self_assessment/#4-1-7 shouldn’t run on worker nodes.

Spreadsheet version of the entire scan:
[scan-mwhvj-9jpmw--2022-02-02-122639.csv](https://github.com/rancher/cis-operator/files/7989786/scan-mwhvj-9jpmw--2022-02-02-122639.csv)

**Comment by rayandas** [comment]
Validated this on Rancher `v2.6.9` (2 worker node, 1 server node) with Kubernetes version `v1.24.8+k3s1`
The issue is not reproducible. It's been fixed already.
