### ISSUE TITLE
check_cafile_permissions and check_cafile_ownership helper script errors

### ISSUE THREAD

**Issue by weistonedawei** [rancher/cis-operator#141]
Unexpected behavior from the following two scripts when $CAFILE is empty.

- [check_cafile_permissions.sh](https://raw.githubusercontent.com/rancher/security-scan/master/package/helper_scripts/check_cafile_permissions.sh)

- [check_cafile_ownership.sh](https://raw.githubusercontent.com/rancher/security-scan/master/package/helper_scripts/check_cafile_ownership.sh)

The following statement returns status code 1 and empty string when $CAFILE is empty (`test -e` is true).

```sh
if test -e $CAFILE; then stat -c permissions=%a $CAFILE; fi
```

I believe the intent is to return status code 0 and an empty string (when $CAFILE is empty) or `permissions=XXX`.

**Comment by MKlimuszka** [comment]
@weistonedawei , which scan are you using and which Rancher version are you on?

**Comment by weistonedawei** [comment]
Rancher versions tried: 2.5.9, 2.5.11, 2.6.3.
Rancher CIS Benchmark releases: 1.0.6, 2.0.1, 2.0.2

The cis-1.6 control files were copied from `kube-bench` main branch (as Rancher CIS Benchmark app custom version example suggested) to make my own custom version.  But, this is incorrect.  Controls files should come from the `kube-bench` branch packaged with Rancher CIS Benchmark app.  As I mentioned in another issue, current Rancher CIS Benchmark is copying from `kube-bench` v0.3.1 control files while the `kube-bench` binary is v0.2.3-rancher-1 (from leodotcloud).

For this issue, I used control files from `kube-bench` repo main branch to make my custom version.  Checks cannot be parsed by `kube-bench` packaged with Rancher CIS Benchmark app.  To work around this problem, I tried the helper scripts, check*.sh.

The helper scripts issues filed here might lead to check state misinterpretation (PASS vs FAIL).

**Comment by weistonedawei** [comment]
Workaround:

To use these two scripts, in `audit` attribute do something like the following:
```txt
audit: '/bin/bash -c ''kubeletcafile=/node$kubeletcafile check_cafile_permissions.sh'' '
```

*Note*:  You may need to provide `/node` prefix since the host machine's root is mounted at /node in security-scan POD.

**Comment by weistonedawei** [comment]
I checked a few security-scan images (v0.2.3, 0.2.4 and 0.2.5) the check_cafile_*.sh scripts do not have execution bit set.  So, any checks using these scripts will result in unreliable check state.

Affected control files:
```
./cis-1.6/node.yaml
./rke-cis-1.6-hardened/node.yaml
./rke-cis-1.6-permissive/node.yaml
```

The best would be to include `kube-bench` from the origin rather than leodotcloud fork.

**Comment by mitulshah-suse** [comment]
@weistonedawei security-scan has been updated to use upstream kube-bench version. Can you please confirm if the issue still exists.

**Comment by weistonedawei** [comment]
@mitulshah-suse You can close this issue.  With kube-bench update to 0.6.8 in security-scan image, it is no longer necessary to use the helper shell scripts (for most cases).

**Comment by mitulshah-suse** [comment]
Closing this based on latest comments.
