### ISSUE TITLE
kube-bench included in security-scan image fails to output version string

### ISSUE THREAD

**Issue by weistonedawei** [rancher/cis-operator#142]
kube-bench included in security-scan image is from leodotcloud fork, which fails to output version string.

Here is how to reproduce it:

```sh
# Download from https://github.com/leodotcloud/kube-bench/releases/download/v0.2.3-rancher-1/kube-bench.tar.gz

# The following command outputs empty string.
./kube-bench version
```

See source [security-scan dockerfile](https://github.com/rancher/security-scan/blob/master/package/Dockerfile).

**Comment by dhruvmewada15** [comment]
@weistonedawei `./kube-bench version` is outputting the empty string as mentioned in the bug description. Wanted to know if you are facing the above said issue while trying to solve something else or just this is the issue that `./kube-bench version` is not outputting version.

**Comment by weistonedawei** [comment]
@dhruvmewada15 While trying to understand unexpected test results and errors (failure to actually run scans), I was trying to pin down the version `kube-bench` used to scan (see the other issues I filed here).  Not print out version string itself is not causing problem but definitely does not give a more positive impression of security.

However, this empty version issue led me to look into the source of `security-scan`, which reveals more serious issues.

I believe the `kube-bench` build script used by leodotcloud fork of `kube-bench` was not setting the version when executing `go build`.

**Comment by samkulkarni20** [comment]
Validation steps:
- Install CIS Benchmark chart with version `2.0.5-rc4` & debug enabled, on a suitable rancher downstream cluster.
- Run a security scan on the downstream cluster.
- Exec into the security scan pod containers & run below command:
`kube-bench version`
- Validate if the version output is `v0.6.8` or not

**Comment by vivek-infracloud** [comment]
**Validated on rancher v2.6.7-rc2**

Validation steps followed

1. Created a rancher server 2.6.7-rc2
2. Provision a downstream k8s cluster v1.24
3. Installed a CIS Benchmark chart version.
4. While scan is running, exec into the security-scan pod and checked the kube-bench version. 
5. kube-bench version shows 0.6.8

kube-bench version command outputs the version string, hence closing the issue.
