### ISSUE TITLE
CIS Benchmark checks can't be scanned by security-scan

### ISSUE THREAD

**Issue by weistonedawei** [rancher/cis-operator#143]
Version: `security-scan` v0.2.6.rc2/master

Problem: Checks can't be scanned correctly

Description:

The `security-scan` [Dockerfile](https://github.com/rancher/security-scan/blob/master/package/Dockerfile) copies versions from `kube-bench` v0.6.6 tag and performs scans using a forked version v0.2.3 from leodotcloud.  There is a mix-and-match here.

The benchmark version checks might use bitmask operator that can't be handled by the forked version of `kube-bench`.  A check's `set` attribute default to true in `kube-bench` v0.6.6 and who know the default value used in the forked `kube-bench` v0.2.3 repo (false, I believe).

**Comment by samkulkarni20** [comment]
Yes @MKlimuszka. We're currently trying to make cis-operator work with the upstream itself, instead of using the fork.

**Comment by dhruvmewada15** [comment]
Duplicate/Similar issue to this https://github.com/rancher/cis-operator/issues/142
PR Raised for the fix: https://github.com/rancher/security-scan/pull/85
Hence Closing
