### ISSUE TITLE
Scan fails for custom benchmark version when /var/log/journal dir is not present

### ISSUE THREAD

**Issue by weistonedawei** [rancher/cis-operator#144]
Description/reproduction:

- Compose custom benchmark version (based on control files the Rancher CIS Benchmark app release)
- Perform a scan using using the custom benchmark
- Scan results show 100% failure.  Drilled down to each check and you would reasonable suspect that checks were not actually run
- It is difficult to catch the error because the PODs terminates in short amount of time
  ```sh
  # loop the following until scanner PODs are running
  ns=cis-operator-system
   pd=($(kubectl get pod -o Name --field-selector=status.phase=Running -n $ns | grep 'sonobuoy-rancher-kube'))
  # Retrieve logs
  kubectl logs -f ${pd[0]} -n $ns -c rancher-kube-bench
  ```
- Error in log file
  ```
  + JOURNAL_LOG=/var/log/journal
  Rancher Kubernetes Version: v1.22.4
  ++ journalctl -D /var/log/journal --lines=0
  ++ grep -s 'No such file or directory'
  ++ wc -l
  + [[ 1 -gt 0 ]]
  + JOURNAL_LOG=/run/log/journal
  + find /etc/kbs/custombenchmark/cfg -name '*.yaml'
  + xargs -n1 sed -i 's|/var/log/journal|/run/log/journal|'
  sed: couldn't open temporary file /etc/kbs/custombenchmark/cfg/sedXVCjyv: Read-only file system
   ```
Cause:

- journal storage is not persistent
- /var/log/journal does not exist
- `security-scan` repo package/run_sonobuoy_plugin.sh tries to modify benchmark version control files that are mounted from ConfigMap
- volumes mounted from ConfigMap resource are read-only since kubernetes 1.11 (I believe)

For discussion/fix:

- Review **`run_sonobuoy_plug.sh`'s** use of `journalctl -D ${JOURNAL_LOG}`.  Maybe `test -d ${JOURNAL_LOG}` is good enough.
- Output error message indicating failure.
- Since only `k3s` tests need to have /var/log/journal strings replaced, maybe limit changes to `k3s` clusters
- Should not change anything silently in custom benchmark version.  In fact, don't do it.  `k3s` tests can use helper scripts.
- Find someway to pass JOURNAL_LOG and other env settings to scans at runtime.  This seems to be difficult since the manifests are controlled by cis-operator controller code.

**Comment by rayandas** [comment]
According to the issue https://github.com/rancher/cis-operator/issues/162 with the fix https://github.com/rancher/security-scan/pull/98, this issue should also be fixed. @weistonedawei Could you please confirm if you can reproduce the issue or not? If yes please provide below details.
- OS system used.
- Version of cis-benchmark and cis-operator.
- Reproducible steps.

**Comment by weistonedawei** [comment]
@rayandas I believe #162 fix will take care of this issue, too.  Although, I feel very strongly that control files, especially custom control files, should not be modified by the scanning code without user knowing just to pass the tests.  Anyway, you can close this issue.  Thanks!

**Comment by rayandas** [comment]
Thanks
