### ISSUE TITLE
CIS charts are not available even after adding the catalog/repo

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#15]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**
- Navigate to Apps --> Repositories -->Add a repo in dashboard URL: https://github.com/prachidamle/charts.git and branch: `cis-v2-chart`
- Go to charts
- CIS benchmark charts are NOT available.

**Expected Result:**
CIS benchmark charts should be available

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `9b6984d5f`
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): imported rks k8s
- Kubernetes version (use `kubectl version`):

```
1.18
```

**Comment by maggieliu** [comment]
Can this be closed then?

**Comment by sowmyav27** [comment]
I have not be able to test the CIS charts by deploying from the dashboard yet. Have been doing it through Helm. Will close this when I can deploy the charts through dashboard

**Comment by sowmyav27** [comment]
**On master-head - commit id: `343b8e19c`**
Currently validating CIS related tests by installing CIS v2 through helm. Closing the issue. will reopen/log new one when charts are available and can be deployed from Dashboard.
