### ISSUE TITLE
Move `rayandas/kube-bench` repo to a Rancher owned repo

### ISSUE THREAD

**Issue by macedogm** [rancher/cis-operator#155]
We should move [rayandas/kube-bench](https://github.com/rayandas/kube-bench/releases/tag/v0.2.3-rancher-3), which contains Murali's modifications, to a repo owned by Rancher to avoid https://github.com/rancher/security-scan/pull/75 from happening again.

Affected line is - https://github.com/rancher/security-scan/blob/72a09cc8d216db94154551d85665cb5ea8b8a6c3/package/Dockerfile#L30 .

**Comment by rayandas** [comment]
https://github.com/rancher/security-scan/pull/85 This PR(use upstream kube-bench) will fix this issue.

**Comment by rayandas** [comment]
Marking this issue as done because it's a duplicate issue of https://github.com/rancher/cis-operator/issues/155 (QA test done)
The fixes went in this PR https://github.com/rancher/security-scan/pull/85
