### ISSUE TITLE
Fix security-scan failures which are occurring after kube-bench and Go version upgrade.

### ISSUE THREAD

**Issue by rayandas** [rancher/cis-operator#156]
Related issue: https://github.com/rancher/cis-operator/issues/142
Related PR: https://github.com/rancher/security-scan/pull/85

**Comment by rayandas** [comment]
**Validation Steps:**
1. Deploy a Rancher Server
2. Create a 4 downstream cluster of following configurations for each rke1, rke2 and k3s:
    - Single node non-hardened cluster
    - Single node hardened cluster
    - Multi node non-hardened cluster (Each node with distinct roles i.e 1 cp, 1 etcd, 1 worker)
    - Multi node hardened cluster (Each node with distinct roles i.e 1 cp, 1 etcd, 1 worker)
3. Install rancher-cis-benchmark:v2.0.5-rc4 in each of the cluster with security-scan v0.2.8-rc3
4. Run CIS scans of all the profiles (1.6 1.20 1.23 permissive and hardened) and observe the results.

**Expected Result:**
All scans should pass

**Comment by vivek-infracloud** [comment]
Validated the security scans on rancher server v2.6.7-rc3 for rke, rke2 and k3s.

Validations steps.
1. Created a rancher server v2.6.7-rc3.
2. Created following **hardened downstream clusters**.
- RKE (Singlenode all role and multinode [1cp, 3worker, 3 etcd]
- RKE2 (Singlenode all role and multinode [1cp, 3 worker, 3 etcd]
- k3s (singlenode all role and multinode [1cp, 3 worker, 3 etcd]

3. Install a rancher-cis-benchmark:v2.0.5-rc4 in each of the cluster with security-scan v0.2.8-rc3.
4. Ran CIS scans of all the following cluster specific hardened profiles.
- **profile-hardened-1.6**
- **profile-hardened-1.20**
- **profile-hardened-1.23**

Result: All the scans passed successfully.

Scan results.
RKE singlenode.
![Screenshot from 2022-07-20 13-51-21](https://user-images.githubusercontent.com/83208989/179982959-e1330d15-178d-470c-840e-f87cc8dbb002.png)

RKE Multinode.
![Screenshot from 2022-07-20 17-59-59](https://user-images.githubusercontent.com/83208989/179983000-f5d31cff-8986-4695-9bfe-9794e210dfd3.png)

RKE2 Singlenode.
![Screenshot from 2022-07-20 13-50-33](https://user-images.githubusercontent.com/83208989/179983056-946ee91c-6b40-4bce-ab31-257c53f32976.png)

RKE2 Multinode.
![Screenshot from 2022-07-20 13-51-07](https://user-images.githubusercontent.com/83208989/179983106-9baeea6b-2238-417a-8e49-34f22b60dc20.png)

**Comment by rishabhmsra** [comment]
On rancher v2.6.7-rc3, created a downstream hardened k3s v1.23.9+k3s1 cluster and ran the permissive and hardened profile scans. All passed successfully:
![k3sscan](https://user-images.githubusercontent.com/36376154/179984212-e5605fc9-c3fd-427c-9370-f70eec78b5a0.png)

**Comment by vivek-infracloud** [comment]
Based on above validations, closing the issue.
