### ISSUE TITLE
STIG Profile requires mounting the `/etc/rancher` directory to the scan pod.

### ISSUE THREAD

**Issue by atoy3731** [rancher/cis-operator#163]
## Issue

For Rancher Federal's STIG implementation to work on top of CIS operator, the scan job requires having the `/etc/rancher` directory added to its list of mounted volumes so it has the access it needs to perform STIG-level scans.

## Suggested Fix

Add the `/etc/rancher` volume mount in the `job.go` file in addition the existing mounts.

**Comment by galal-hussein** [comment]
This PR should fix the problem https://github.com/rancher/cis-operator/pull/164/files

**Comment by cwayne18** [comment]
Can we mark this as closed since it's been merged, or does it need to be part of a release process before marking closed?

**Comment by galal-hussein** [comment]
@cwayne18 I assigned 2.7.0 milestone to it so that it can be picked up by QA

**Comment by vivek-infracloud** [comment]
Validated the issue on rancher v2.7.0-rc3

Validation steps

1. Created a rancher server v2.7.0-rc3
2. Provisioned a k8s cluster v1.24.6+rke2r1.
3. Launched the CIS scan for rke2 scan profile `rke2-cis-1.23-profile-permissive` available for 2.7.0
4. In the pods view, located the `security-scan-runner` pod launched and in the pod spec checked the  `rke2-root-config` volume mount is present.

Hence, closing the issue.
