### ISSUE TITLE
Env CIS_OPERATOR_DEBUG cann't be set

### ISSUE THREAD

**Issue by weistonedawei** [rancher/cis-operator#167]
Minor issue.

Cannot enable cis-operator debugging by setting CIS_OPERATOR_DEBUG env.  See code [here](#https://github.com/rancher/cis-operator/blob/1c39b1eec89cb15ad42019b9f7ff05d0fef4b6b6/main.go#L99).
All attempts setting CIS_OPERATOR_DEBUG: to true{TRUE}, "true" and "'true'" failed

The work around is edit cis-operator deployment and add command: ["cis-operator"] and args: ["--debug"] to container spec to enable debug logging.

**Comment by vardhaman22** [comment]
I tried setting the ENV variable ```export CIS_OPERATOR_DEBUG="true"``` and running ```go run main.go``` it worked as expected.
If we need to add the debug env variable to cis operator deployment in cis-benchmark chart then for that i have created this PR:
https://github.com/rancher/charts/pull/2227
please check the following commit for that.
https://github.com/rancher/charts/pull/2227/commits/28971511f07e37be00844503d4b4fd29d204a621

**Comment by vivek-infracloud** [comment]
Validated the issue on rancher v2.7.0. Debug logs are now visible after setting the CIS_OPERATOR_DEBUG="true"

validation steps:
1. Created a rancher server v2.7.0
2. Provisioned a RKE1 downstream cluster v1.24.
3. Installed a CIS Benchmark chart v3.0.1-rc1
4. Changed a CIS_OPERATOR_DEBUG flag to "true".
5. Ran CIS scan.
6. Scan shows the debug logs along with the info logs.
![Screenshot from 2022-12-12 11-57-28](https://user-images.githubusercontent.com/83208989/206984733-d6be22dc-4786-4d17-b3d8-bbb397bbc358.png)

Closing the issue.
