### ISSUE TITLE
[Backport v2.6] CIS benchmark rke2 hardened fails in 5.3.1 with cilium as CNI

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/cis-operator#168]
Backported from https://github.com/rancher/cis-operator/issues/154

Just updated to rancher 2.6.5 and deployed cis benchmark 2.0.4. scanned the downstream cluster and got an error for 5.3.1 (cni does not support network policies).

This is a false positive as cilium does support and has enabled network policies.

Seems this is the root cause https://github.com/rancher/security-scan/blob/9116bbe07914478ca79e0756a4798fa41a49a95e/package/cfg/rke2-cis-1.6-hardened/policies.yaml#L200

Could we get this "fixed" in a way that is also accepts cilium and probably all other CNIs that are available and supported for RKE2 and that have support for network policies?

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6-head(8048eee)
Downstream cluster : RKE2 hardened cluster(1-cp, 1-etcd, 1-w) -> v1.24.8+rke2r1

**Steps followed:**
- Provisioned RKE2 hardened clusters using below CNIs ->
  - canal
  - cilium
  - calico
  - multus,canal
  - multus,cilium
  - multus,calico
- Installed CIS benchmark chart `2.1.1-rc1` and ran the scan using `rke2-cis-1.23-profile-hardened` profile.

**Result:**
- Scan passed successfully.
- 5.3.1 passed on all the clusters.
![scans](https://user-images.githubusercontent.com/36376154/206695446-f05d2bb1-276f-45a2-895c-83dc180cc86f.png)

![pass](https://user-images.githubusercontent.com/36376154/206695263-7a99e85b-6fdb-437f-951c-553978ba5b56.png)
