### ISSUE TITLE
K3s hardened profiles fail checks `4.2.1`, `4.2.2` and `4.2.3` on `etcd` node for multi node cluster

### ISSUE THREAD

**Issue by macedogm** [rancher/cis-operator#169]
Further details are available in https://github.com/rancher/rancher/issues/37493#issuecomment-1269938970.

On a K3s multi node (1 etcd, 1 cp, 1 worker) hardened cluster, checks `4.2.1`, `4.2.2` and `4.2.3` will fail on the `etcd` node, because they are checking for `apiserver` specific configurations and the `apisever` is disabled on K3s `etcd` node. See the images below for extra details.

![](https://user-images.githubusercontent.com/17654553/194310011-cf40d751-6e02-4f97-b5f4-ba1cbf79ebbb.png)

![](https://user-images.githubusercontent.com/17654553/194310211-ec3c6db8-1aa0-43f4-a5da-f4da0319be43.png)

Affected profiles:

- [k3s-cis-1.6-hardened](https://github.com/rancher/security-scan/blob/master/package/cfg/k3s-cis-1.6-hardened/node.yaml#L191-L254)
- [k3s-cis-1.20-hardened](https://github.com/rancher/security-scan/blob/master/package/cfg/k3s-cis-1.20-hardened/node.yaml#L195-L258)
- [k3s-cis-1.23-hardened](https://github.com/rancher/security-scan/blob/master/package/cfg/k3s-cis-1.23-hardened/node.yaml#L194-L257)

**Comment by prachidamle** [comment]
@macedogm Can we add more environment details and CIS chart version used to reproduce this issue please?

**Comment by cwayne18** [comment]
At this point 1.23 should only be run against k8s 1.25+, as it checks for PSA rather than PSP

**Comment by macedogm** [comment]
Just a note, the reported failures also happen with `k3s-cis-1.6-hardened` and `k3s-cis-1.20-hardened` and they are related to etcd.

**Comment by prachidamle** [comment]
@macedogm Can you please review the PR if it fixes the issue https://github.com/rancher/security-scan/pull/96

**Comment by prachidamle** [comment]
This can be tested when this Charts PR is merged in https://github.com/rancher/charts/pull/2149

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(0dcfd16)

Steps followed:
- Provisioned k3s hardened cluster -> `v1.24.6+k3s1` (1-cp, 1-e, 1-w)
- Installed CIS benchmark 3.0.0-rc7 chart.
- Ran `k3s-cis-1.23-profile-hardened` scan.

Result:
- Scan passed successfully:

![hardened-scan](https://user-images.githubusercontent.com/36376154/196173782-f33b0520-fdd3-4f43-8fce-ad2b3fdbf048.png)
