### ISSUE TITLE
[Backport 2.6] K3s hardened profiles fail checks 4.2.1, 4.2.2 and 4.2.3 on etcd node for multi node cluster

### ISSUE THREAD

**Issue by mitulshah-suse** [rancher/cis-operator#170]
Backported from https://github.com/rancher/cis-operator/issues/169

Further details are available in https://github.com/rancher/rancher/issues/37493#issuecomment-1269938970.

On a K3s multi node (1 etcd, 1 cp, 1 worker) hardened cluster, checks 4.2.1, 4.2.2 and 4.2.3 will fail on the etcd node, because they are checking for apiserver specific configurations and the apisever is disabled on K3s etcd node. See the images below for extra details.

![](https://user-images.githubusercontent.com/17654553/194310011-cf40d751-6e02-4f97-b5f4-ba1cbf79ebbb.png)

![](https://user-images.githubusercontent.com/17654553/194310211-ec3c6db8-1aa0-43f4-a5da-f4da0319be43.png)

Affected profiles:

[k3s-cis-1.6-hardened](https://github.com/rancher/security-scan/blob/master/package/cfg/k3s-cis-1.6-hardened/node.yaml#L191-L254)
[k3s-cis-1.20-hardened](https://github.com/rancher/security-scan/blob/master/package/cfg/k3s-cis-1.20-hardened/node.yaml#L195-L258)
[k3s-cis-1.23-hardened](https://github.com/rancher/security-scan/blob/master/package/cfg/k3s-cis-1.23-hardened/node.yaml#L194-L257)

**Comment by rishabhmsra** [comment]
Validated on rancher v2.6-head(8048eee)

Steps followed:
- Provisioned k3s hardened cluster -> `v1.24.8+k3s1` (1-cp, 1-e, 1-w)
- Installed CIS benchmark `2.1.1-rc1` chart.
- Ran k3s-cis-1.23-profile-hardened scan.

Result:
- Scan passed successfully:

![k3spass](https://user-images.githubusercontent.com/36376154/206694233-086339ef-68dd-45f9-bd4a-153307f27d9a.png)
