### ISSUE TITLE
[Backport v2.6] Use bitmasks instead of multiple comparisions with "or" for checking file permissions are set to 644 or more restrictive

### ISSUE THREAD

**Issue by rayandas** [rancher/cis-operator#174]
Backport issue for https://github.com/rancher/cis-operator/issues/120

**Comment by vivek-infracloud** [comment]
Tested this issue on rancher v2.6.9 on k8s v1.24.8+rke2r1 with CIS Benchmark chart v2.1.1-rc3.

Tests have passed and chart scan behaviour is as expected. Hence closing this issue.
