### ISSUE TITLE
[Backport v2.6] File permissions check don't always seem to work properly - rke2

### ISSUE THREAD

**Issue by rayandas** [rancher/cis-operator#175]
Backport of https://github.com/rancher/cis-operator/issues/125

**Comment by vivek-infracloud** [comment]
Tested the issue on rancher 2.6-head and k8s version v1.24.8+rke2r1.

Test steps:

- Created a rancher server v2.6-head
- Provisioned a 3 node k8s cluster v1.24.8+rke2r1.
- Installed a CIS Benchmark v2.1.1-rc3
- Ran a CIS Profile 
- Tests 1.1.10, 1.1.20, 1.1.21 shows warning.

![Screenshot from 2023-01-10 14-02-11](https://user-images.githubusercontent.com/83208989/211500745-495af284-e3f0-472f-947c-af140a73eb45.png)

**Comment by vivek-infracloud** [comment]
The above tests are still not passing, hence reopening the issue.

**Comment by vivek-infracloud** [comment]
Tested the issue on rancher 2.6-head and k8s version v1.24.9+rke2r2.

Test steps:

- Created a rancher server v2.6-head
- Provisioned a 3 node k8s cluster v1.24.9+rke2r2.
- Installed a CIS Benchmark v3.0.1-rc3
- Ran a CIS Profile 
- Tests 1.1.10, 1.1.20, 1.1.21 are passing.
![Screenshot from 2023-01-27 18-11-47](https://user-images.githubusercontent.com/83208989/215090359-ba79ef8e-ef6b-440e-aa30-e01f7473a8fb.png)
![Screenshot from 2023-01-27 18-12-00](https://user-images.githubusercontent.com/83208989/215090368-849e6e34-c39b-4908-80d6-c081e3004fa6.png)

Hence closing the issue.
