### ISSUE TITLE
[Backport] cis-operator:v1.0.6 contains a number of High CVEs

### ISSUE THREAD

**Issue by rayandas** [rancher/cis-operator#177]
Backport issue of https://github.com/rancher/cis-operator/issues/138

**Comment by rayandas** [comment]
Waiting for this PR to get merged https://github.com/rancher/cis-operator/pull/173. 
Then this issue will be ready for testing.

**Comment by vivek-infracloud** [comment]
```
rancher/cis-operator:v1.0.11-rc3 (suse linux enterprise server 15.4)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

Closing this issue since CVEs are fixed.
