### ISSUE TITLE
[Backport v2.6] Downloaded CIS v2 report does not have the cis-1.5-profile or the benchmark value

### ISSUE THREAD

**Issue by rayandas** [rancher/cis-operator#180]
Backport issue of https://github.com/rancher/cis-operator/issues/39

**Comment by vivek-infracloud** [comment]
Tested the issue on rancher v2.6-head with CIS Benchmark chart v2.1.1-rc4.

Downloaded report of the CIS scan. The name of report contains the CIS benchmark profile name. 
Hence issue can be closed.
![Screenshot from 2023-01-27 17-01-37](https://user-images.githubusercontent.com/83208989/215079192-3054a3d9-340e-42ef-9e95-2ad9ff4db4ef.png)
