### ISSUE TITLE
Incorrect scanning on non-etcd DB for k3s-cis-1.23 scans.

### ISSUE THREAD

**Issue by dereknola** [rancher/cis-operator#187]
Background:
We have a helper script that give the "right answer" whenever you run a non-etcd DB for the k3s etcd checks.
Error:
When cis-1.23 was published there was a change from cis-1.6 to cis-1.23 for check 1.2.29. Previously the check was for both `etcd-certfile` and `etcd-keyfile`  see [here](https://github.com/dereknola/security-scan/blob/master/package/cfg/k3s-cis-1.6-hardened/master.yaml#L773) . Now, in cis-1.23, the check is only for [`etcd-certfile` only](https://github.com/dereknola/security-scan/blob/master/package/cfg/k3s-cis-1.23-hardened/master.yaml#L782). The helper script [here](https://github.com/dereknola/security-scan/blob/master/package/helper_scripts/check_for_k3s_etcd.sh#L40) needs to be modified to account for it.

**Comment by andypitcher** [comment]
@dereknola is this issue still to be considered given our recent work ?

**Comment by dereknola** [comment]
Still relevant, but will be closed with https://github.com/rancher/security-scan/pull/221

**Comment by andypitcher** [comment]
@dereknola closing since the above issue has been merged.
