### ISSUE TITLE
rke-cis-1.6-hardened test 1.2.35 state:warn

### ISSUE THREAD

**Issue by t80027t** [rancher/cis-operator#189]
Rancher 2.6.6
CIS Scanner 2.0.4

---

Test 1.2.35 under rke-cis-1.6-hardened checks kube-apiserver applies a valid cipher suite based on the value of command line flag `--tls-cipher-suites`.

I have manually checked this for all kube-apiservers on the target nodes and it looks fine based on the guidance, yet the `state` of the test result is marked as `warn`.

```

{"id":"1.2.35","description":"Ensurethat the API Server only makes use of Strong Cryptographic Ciphers (Automated)","remediation":"Edit the API server pod specification file /etc/kubernetes/manifests/kube-apiserver.yaml\non the master node and set the below parameter.\n--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM\n_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM\n_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM\n_SHA384\n","state":"warn","node_type":["master"],"audit":"/bin/ps -ef | grep kube-apiserver | grep -v grep","audit_config":"","test_info":["Edit the API server pod specification file /etc/kubernetes/manifests/kube-apiserver.yaml\non the master node and set the below parameter.\n--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM\n_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM\n_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM\n_SHA384\n"],"commands":null,"config_commands":null,"actual_value_per_node":{"host0":"","host1":"","host2":""},"expected_result":"","test_type":"","scored":false}]}

```

The only other test under this group which uses the `op: valid_elements` is 4.2.13, which is the same check but for the kubelet process. However, for test 4.2.13, it additionally specified `path: '{range .tlsCipherSuites[:]}{}{'',''}{end}'`. Maybe this is missing from test 1.2.35 and not allowing it to pass?

**Comment by vardhaman22** [comment]
Hi @t80027t 
This issue is not present in future release of rancher-cis-benchmark chart. 
Please try upgrading the chart to any 2.1.x version.

**Comment by mitulshah-suse** [comment]
Closing this issue, since there are no further updates.
