### ISSUE TITLE
State transitions for CIS v2 scans are confusing

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#19]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Repo: https://github.com/prachidamle/charts.git branch: civ-v2-chart
- Run a scan by creating a cluster Scan CR.
- The scan's state changes from Active --> Running --> Active

- For example, in a scenario when 2 ClusterScan CRs are created in parallel - scan-1 and scan-2
- Scan-1 is seen in Running state and Scan -2 is seen in Active state.
- When Scan-1 has finished, the state of Scan-1 is now Active
- Scan-2 now changes to Running --> Active state

**Expected Result:**
Transition state of the clusterScan can be made better

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit id: `8d9cedd `
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom cluster - 8 nodes - 3 etcd, 2 control and 3 worker nodes.
- Kubernetes version (use `kubectl version`):

```
1.18
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by prachidamle** [comment]
This issue has been fixed and available to test via the new tag:    
- repository: rancher/cis-operator
- tag: v0.0.4
- The rancher-cis-benchmark chart has been updated to use this tag. https://github.com/rancher/charts/pull/586


Fix provided:
- A new `status.display.state` field has been added to the ClusterScan CRD and this will contain the state of the ClusterScan: pass/fail/error/reporting.
This state will be displayed under STATUS column of the ClusterScan list on Dashboard.

Example: Here is how the clusterscan fields will be displayed that shows the the STATUS field to reflect the state of the scan as (pass/fail/error/reporting)

```
$ kubectl --kubeconfig ~/.kube/test_config_master  get clusterscans 

NAME           STATUS   CLUSTERSCANPROFILE       TOTAL   PASS   FAIL   SKIP   NOT APPLICABLE   LASTRUNTIMESTAMP
rke-cis        fail     rke-profile-hardened     92      59     13     0      20               2020-09-05T01:18:28Z
rke-cis-perm   pass     rke-profile-permissive   92      58     0      0      34               2020-09-05T01:19:36Z
run-eks-1.0    error 

```
The STATE field on Dashboard may not yet reflect this `status.display.state` value(possibly needs a UI update?), but the STATUS field will demo the state transitions.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `3ca11da829 `**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- Run a scan by creating a cluster Scan CR.
- The scan's state changes from Active --> Running --> Pass/Fail/Error
- when 2 ClusterScan CRs are created in parallel - scan-1 and scan-2
- Scan-1 is seen in Running state and Scan -2 is seen in Active state.
- When Scan-1 has finished, the state of Scan-1 is now Pass
- Scan-2 now changes to Running --> Pass state

**Expected:**
Can we have the initial state of the scan as `Created`/`Pending` instead of `Active` ?

**Comment by prachidamle** [comment]
We will be having following states:
"Active"  - this is the default state set by steve/wrangler api for a new object
"Pending" - clusterscan pending to be run
"Running" - scan running
"Reporting" - report generation in process
"Pass" / "Fail" / "Error" - scan complete

**Comment by sowmyav27** [comment]
**On master-head - commit id: `e919796c`** - issue is not seen fixed.

- As a standard user Deployed CIS benchmark chart on a user cluster. images:
```
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.5
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.0
  sonobuoy:
    repository: rancher/sonobuoy-sonobuoy
    tag: v0.16.3
```

- Run a scan by creating a cluster Scan CR.
- The scan's state changes from Active --> Running --> Pass/Fail/Error
- when 2 ClusterScan CRs are created in parallel - scan-1 and scan-2
- Scan-1 is seen in Running state and Scan -2 is seen in **Pending** state.
- When Scan-1 has finished, the state of Scan-1 is now Pass
- Scan-2 now changes to Running --> Pass state
