### ISSUE TITLE
Bump CIS GKE benchmark

### ISSUE THREAD

**Issue by niusmallnan** [rancher/cis-operator#192]
In Rancher v2.7.2, only the GKE 1.0 profile can be used for scanning. This version is too old to support the GKE version in the Rancher support matrix.

The kube-bench already supports [CIS GKE benchmark 1.2.0](https://github.com/aquasecurity/kube-bench/tree/main/cfg/gke-1.2.0).
However, the recently available version should be [1.4.0](https://www.cisecurity.org/benchmark/kubernetes). 

In order to make the GKE benchmark more sensible integration with Rancher. Suggest the following to-do list:
1. [Required] Expose the GKE 1.2.0 benchmark in Rancher and declare the GKE version it supports.
2. [Required] Remove the GKE 1.0 benchmark, it should no longer work for any GKE version.
3. [Optional] Introducing the GKE 1.4.0 benchmark

**Comment by Priyashetty17** [comment]
This has been validated [here](https://github.com/rancher/rancher/issues/41886). 
**Note**: This was not implemented:  [Optional] Introducing the GKE 1.4.0 benchmark

**Comment by rayandas** [comment]
GKE 1.4.0 is not yet released by kube-bench. Hence we are not able to add it to Rancher right now.

**Comment by rayandas** [comment]
Closing this PR on behalf of @Priyashetty17 as she doesn't have the permission to close this issue. The QA validation is already done as she mentioned above.
