### ISSUE TITLE
Add a E2E smoke test to confirm cis-operator build is stable

### ISSUE THREAD

**Issue by andypitcher** [rancher/cis-operator#209]
In order to test `cis-operator` build and validate the version bumps and the PRs of renovate when there is a new package version, it would be relevant to add a E2E smoke test in` scripts/` . 
e2e would be then run to test whether the cis-operator build is stable or not.

Here are the possible tests:

1. Create a kind cluster
2. Deploy the cis-operator
4. Read the logs

**Comment by pjbgf** [comment]
Fixed as per #229
