### ISSUE TITLE
Improve security-scan execution time and conditions accuracy for k3s

### ISSUE THREAD

**Issue by andypitcher** [rancher/cis-operator#222]
In K3s, the kubernetes components are all packaged in one binary - which makes it non-trivial to analyze the kubernetes binaries by running `ps -eF etcd`.

To overcome this limitation and test whether etcd runs on a K3s cluster, `rancher/security-scan/package/run_sonobuoy_plugin.sh` reads K3s' logs through`journalctl`, here is one example:

```
# etcd
if [[ "${OVERRIDE_BENCHMARK_VERSION}" != "" ]]; then
  if [[ "$(ps -e | grep etcd | wc -l)" -gt 0  ]]  || [[ "$(journalctl -D $JOURNAL_LOG -u k3s -u k3s-agent | grep -wv 'No entries' | grep -wv 'Logs begin' | wc -l)" -gt 0 ]]; then
    echo "etcd: Using OVERRIDE_BENCHMARK_VERSION=${OVERRIDE_BENCHMARK_VERSION}"
```

The issue with the command `journalctl -D $JOURNAL_LOG -u k3s -u k3s-agent | grep -wv 'No entries' | grep -wv 'Logs begin' | wc -l` is that it will go through all k3s' logs to find ALL occurrences complying to `-u k3s -u k3s-agent | grep -wv 'No entries' | grep -wv 'Logs begin'`. 
Going through all the available logs can be time consuming, where we only need to confirm that we're on a K3s.

Here are some tests that show the execution time improvements (-30 sec) before and and after the changes:

Before:
```
root@k3s-1:~# time journalctl -D /var/log/journal/ -u k3s -u k3s-agent | grep -wv 'No entries' | grep -wv 'Logs begin' |wc -l
1133203
real        0m26.854s
user        0m21.576s
sys        0m4.878s
```

After:
```
root@k3s-standalone1:~# time journalctl -D /var/log/journal/ -u k3s | grep -m1 "Managed etcd cluster initializing" | wc -l
1
real        0m0.010s
user        0m0.006s
sys        0m0.006s
```

The improvement here is to use `grep -m1 "Managed etcd cluster initializing"` which stops after 1 selected line when "Managed etcd cluster initializing" is found. Looking for "Managed etcd cluster initializing" is also more accurate since it validates `k3s + etcd`. Finally the condition is still satisfied since `wc -l` value has to be greater than 0.

```
root@k3s-standalone1:~# time journalctl -D /var/log/journal/ -u k3s | grep -m1 "Managed etcd cluster initializing"
Aug 04 09:26:41 k3s-standalone1 k3s[2181]: time="2023-08-04T09:26:41Z" level=info msg="Managed etcd cluster initializing"
```

Several similar commands are present in [run_sonobuoy_plugin.sh](https://github.com/rancher/security-scan/blob/master/package/run_sonobuoy_plugin.sh) and [check_for_k3s_etcd.sh](https://github.com/rancher/security-scan/blob/f9821a57f39a9d3a3848e74da6e0c7287efa8448/package/helper_scripts/check_for_k3s_etcd.sh#L14).

A PR will be crafted to handle the majority of these commands.

**Comment by Priyashetty17** [comment]
@samjustus @sowmyav27 Should this be assigned to Infracloud? I thought cis dev and testing moved to Infracloud?

**Comment by vivek-shilimkar** [comment]
Tested the security-scan execution time on rancher v2.8.0

k8s version : v1.27.8+k3s2
CIS Benchmark chart version : 5.1.0-rc2

Scan runs successfully. Hence closing the issue.
