### ISSUE TITLE
[v2.8] Add EKS 1.2.0 

### ISSUE THREAD

**Issue by rayandas** [rancher/cis-operator#233]
EKS 1.2.0 configs were added in kube-bench 6 months back https://github.com/aquasecurity/kube-bench/tree/main/cfg/eks-1.2.0
We should introduce it in security-scan. 

TODO:

- [x] Update kube-bench and sonobuoy versions and introduce eks-1.2.0 benchmark in security-scan.
- [x] When the security-scan PR is merged, create a new tag.
- [x] Update eks templates to 1.2.0 (similar to https://github.com/rancher/charts/pull/2812) and bump security-scan version and introduce a new CIS-Benchmark chart.

**Comment by vivek-shilimkar** [comment]
Tested the CIS Benchmark version update for eks. 

rancher version : v2.8.0
k8s version : v1.27.8-eks-8cb36c9
CIS Chart version : 5.1.0-rc2
Benchmark version : eks-1.2.0

Updated EKS template 1.2.0 is working as expected. Hence, closing the issue.
