### ISSUE TITLE
[Backport v2.7] CIS Scan failures for k3s scan profiles and other test warnings on Oracle Linux 9.1

### ISSUE THREAD

**Issue by vivek-shilimkar** [rancher/cis-operator#260]
Backport of https://github.com/rancher/cis-operator/issues/255

**Comment by rishabhmsra** [comment]
Validated on rancher v2.7-head(f963489)
- Provisioned k3s v1.26.11+k3s2 k8s node driver cluster(1-cp, 1-e, 1-w)
- Installed CIS benchmark chart version 4.3.0-rc4
- Ran scan using cis k3s-cis-1.8-profile-permissive profile.

Result:
- Scan passes successfully, hence closing the issue.
