### ISSUE TITLE
[2.7] CIS scan fails on k3s v1.23 clusters.

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/cis-operator#262]
**Rancher Server Setup**

- Rancher version: v2.7-head(f963489)
- Installation option (Docker install/Helm Chart): Docker
  - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**

- Kubernetes version: v1.23.17+k3s1
- Cluster Type (Local/Downstream): Downstream
If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS node driver

**User Information**

- What is the role of the user logged in? : Admin

**Describe the bug**
- On K3s v1.23 k8s cluster, cis-1.23 permissive profile scan fails with below result:
```
Mixed
4.1.7	Ensure that the certificate authorities file permissions are set to 644 or more restrictive (Manual)
```

**To Reproduce**

- Create a rancher server v2.7-head(f963489)
- Provision node driver or custom k3s v1.23.17+k3s1 cluster(1-cp, 1-e, 1w) 
- Install cis-benchmark-chart 4.3.0-rc4 on the cluster.
- Run scan with k3s-cis-1.23-permissive profile.

**Result**
- Observe that 4.1.7 shows Mixed result.

**Expected Result**
- All tests should pass.

**Comment by vivek-shilimkar** [comment]
On k3s v1.23.17+k3s1 ran v1.23 permissive profile scan and it passed successfully:
![Screenshot from 2024-03-19 14-10-09](https://github.com/rancher/cis-operator/assets/83208989/4b6670b2-a526-4689-8a97-5b9203901c34)

![Screenshot from 2024-03-19 14-10-30](https://github.com/rancher/cis-operator/assets/83208989/8a2ce771-ca28-4a46-a6ce-5864e48a7487)
