### ISSUE TITLE
Review `tls-cipher-suites` rules and documentation

### ISSUE THREAD

**Issue by pjbgf** [rancher/cis-operator#268]
k3s and rke2 have stronger default settings which by default already comply with CIS Benchmark recommendations.
However, at times it is not clear to the end user that this is the case:

![image](https://github.com/rancher/cis-operator/assets/5452977/6fbd7fee-077c-4bb4-b5ea-023a16ceb1b8)

The rule description does not seem to align with the [documentation](https://docs.rke2.io/security/cis_self_assessment123#1232):

> Remediation: By default, RKE2 explicitly doesn't set this flag. No manual remediation needed.

This issue tracks the improvement of both documentation and rules to make them clearer to end users.

**Comment by andypitcher** [comment]
The documentation update for the related checks will be handled in https://github.com/rancher/rancher/issues/45318. I'm Closing this issues.
