### ISSUE TITLE
CIS v2: Support Scheduled cluster scan that runs periodically

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#27]
- Add ability to setup a periodic scheduled clusterscan

**Comment by prachidamle** [comment]
Will be delivered with the next chart version of rancher-cis-benchmark

**Comment by sowmyav27** [comment]
**On 2.5-head, using charts: `rancher-cis-benchmark:1.0.300`**

- P1 use case works:
- Create a scan CR.
- Enable schedule scan on the scan cr. Give in the cron value and retention count. 
- Scans get created. 
- Issues related have been logged separately.
- Closing this one.
