### ISSUE TITLE
CIS v2: Add ability to configure alerts 

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#28]
Add ability to configure Alerts when the clusterscan failed/completed

**Comment by sowmyav27** [comment]
**On 2.5-head, using charts: `rancher-cis-benchmark:1.0.300`**

- P1 use case works:
- Enable monitoring/Alerting on the cluster.
- Create a scan CR.
- Enable schedule scan on the scan cr. Give in the cron value and retention count. Enable Alerting .
- Scans get created. And Alerts are received.
- Issues related to this epic have been logged separately.
- Closing this one.
