### ISSUE TITLE
[v2.8] Fix K3s Profiles audit and remediation for 1.1.20 and 1.1.21 checks

### ISSUE THREAD

**Issue by vardhaman22** [rancher/cis-operator#290]
currently the audit command and remediation for 1.1.20 and 1.1.21 check for k3s profiles is not correct. And the check is always in **warn state** even if the criterias of the checks are met.

Since the audit command is present the checks should pass if the permission of the required files met the criteria.

**Comment by vivek-shilimkar** [comment]
Audit and remediation both are fixed for k3s profiles. Hence, closing the issue
