### ISSUE TITLE
[Backport] [v2.7] Fix K3s Profiles audit and remediation for 1.1.20 and 1.1.21 checks

### ISSUE THREAD

**Issue by vardhaman22** [rancher/cis-operator#291]
backport for issue: https://github.com/rancher/cis-operator/issues/290

**Comment by vivek-shilimkar** [comment]
Audit and Remediation for k3s clusters are updated in k3s profiles `1.23`, `1.24`, `1.7` and `1.8`. Audit is as expected in scan number 1.1.20 and 1.1.21. However, the remediation doesn't work. Running the remediation command results in following error -
`find: missing argument to -exec'`

**Comment by vivek-shilimkar** [comment]
Audit and remediation both are fixed for k3s profiles. Hence, closing the issue
