### ISSUE TITLE
[v2.7]  Remove support for CIS scan profile and benchmarks for versions prior to k8s 1.23

### ISSUE THREAD

**Issue by vardhaman22** [rancher/cis-operator#293]
## Description
* Need to remove the CIS scan for k8s versions which the `v2.7.x` rancher does not support.

## Reference
* [Rancher Support Matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-12/)
* [Kubebench (CIS) support Matrix](https://github.com/aquasecurity/kube-bench/blob/main/docs/platforms.md)

**Comment by vivek-shilimkar** [comment]
Support for CIS scan profiles and benchmarks for versions prior to k8s 1.23 is removed. 
![Screenshot from 2024-04-15 15-52-09](https://github.com/rancher/cis-operator/assets/83208989/e63a1188-afac-4f13-9be7-2edd9485c571)

Hence closing the issue.
