### ISSUE TITLE
[v2.9] Bump cis-operator and security-scan to the latest version in cis-benchmark chart

### ISSUE THREAD

**Issue by vardhaman22** [rancher/cis-operator#330]
new versions of cis-operator and security-scan is available and needed to be bumped in the rancher-cis-benchmark chart.

**Comment by vardhaman22** [comment]
for the new security scan tags many checks of the rke2 and k3s profiles are updated so all those profiles needs to be verified.
- permissive and hardened k3s profiles 1.23, 1.24, 1.7, 1.8
- permissive and hardened rke2 profiles 1.23, 1.24, 1.7, 1.8
also this [PR](https://github.com/rancher/security-scan/pull/218) fixes some issue with k3s checks on sles so that also needs to be verified.

**Comment by vivek-shilimkar** [comment]
Validated on rancher v2.9.1-rc1

- Created RKE1 v1.30.3rancher1-1 node driver and hardened clusters.
- Created RKE2 v1.30.2+rke2r1 node driver and hardened clusters.
- Created K3s v1.30.2+k3s2 node driver and hardened clusters.
- Installed CIS 6.1.0-rc2 chart on all the clusters.

Following expected failures are 

- 4.1.7 fails on RKE1 hardened 
- 1.1.1, 1.1.3, 1.1.5, 1.1.7 fails on RKE2 node driver cluster which is expected.
