### ISSUE TITLE
[Backport] [v2.8] Bump cis-operator and security-scan to the latest version in cis-benchmark chart

### ISSUE THREAD

**Issue by vardhaman22** [rancher/cis-operator#331]
backport: https://github.com/rancher/cis-operator/issues/330

**Comment by vardhaman22** [comment]
for the new security scan tag many checks of the rke2 and k3s profiles are updated so all those profiles needs to be verified.
- permissive and hardened k3s profiles  1.7, 1.8
- permissive and hardened rke2 profiles 1.7, 1.8

also this [PR](https://github.com/rancher/security-scan/pull/218) fixes some issue with k3s checks on sles so that also needs to be verified.

**Comment by rishabhmsra** [comment]
Validated on rancher v2.8.7-rc2

- Created RKE1 v1.25.16-rancher2-3 and v1.28.12-rancher1-1 node driver and hardened clusters (1-cp, 1-e, 1-w)
- Created RKE2 v1.28.11+rke2r1 and v1.25.16+rke2r1	node driver and hardened clusters.
- Created K3s v1.28.11+k3s2	and v1.25.16+k3s4	node driver and hardened clusters.
- Installed CIS 5.3.0-rc2 chart on all the clusters.
- 4.1.7 fails on RKE1 hardened cluster, which is expected.
- 1.1.1, 1.1.3, 1.1.5, 1.1.7 fails on RKE2 node driver cluster which is expected.

RKE1 node driver and hardened clusters scans:

![rke125nd](https://github.com/user-attachments/assets/51a42d49-fa6f-4a5d-8211-f8da9035714d)

![rke125-hardened](https://github.com/user-attachments/assets/2de5c1cb-265d-42d2-8111-ff6d0db6ddca)

![rke1-128-nd](https://github.com/user-attachments/assets/28959403-aeee-4415-8d4b-6c57287836a9)

![rke1-128-hardened](https://github.com/user-attachments/assets/a1d30fa7-18c6-4535-aa77-1d518f5a3fe7)

--------

RKE2 node driver and hardened clusters scan :

![rke2-25-nd](https://github.com/user-attachments/assets/99e8cc17-963c-4638-aaa4-9f313310b109)

![rke2-25-hardened](https://github.com/user-attachments/assets/0bbd14dd-42bd-425f-a379-25eeb4106fd3)

![rke2-128-hardened](https://github.com/user-attachments/assets/c5334708-2168-431b-94da-b3db39288004)

![rke2-nd-128](https://github.com/user-attachments/assets/c7e1d0e3-7931-4c9f-96de-7dc3fe820722)

-------

K3s node driver and hardened clusters scan :

![k3s-nd](https://github.com/user-attachments/assets/24a9ac4b-9dc7-4035-a8af-c4e9ecb66ef7)

![k3s-25-hardened](https://github.com/user-attachments/assets/0c6e85ce-dc31-4998-b6c1-e845a93e0095)

![k3s1](https://github.com/user-attachments/assets/b8ed6f31-a77f-4c16-b454-9b114d6bcfb0)

![k3s2](https://github.com/user-attachments/assets/588c5a14-1705-4d67-bb8f-59153ae22288)
