### ISSUE TITLE
Add automated tests to CIS-operator

### ISSUE THREAD

**Issue by maggieliu** [rancher/cis-operator#34]
Add unit tests in the operator repo

**Comment by MKlimuszka** [comment]
@mitulshah-suse , you can decide if adding more automated testing to cis-operator is worth pursuing.

**Comment by doflamingo721** [comment]
I have identified the following unit tests which can be added to the cis-operator repo. 

Following are the files from which I have identified these tests:
1. https://github.com/rancher/cis-operator/blob/master/pkg/securityscan/jobHandler.go
2. https://github.com/rancher/cis-operator/blob/master/pkg/securityscan/podHandler.go
3. https://github.com/rancher/cis-operator/blob/master/pkg/securityscan/scanHandler.go
4. https://github.com/rancher/cis-operator/blob/master/pkg/securityscan/scheduledScanHandler.go
5. https://github.com/rancher/cis-operator/blob/master/pkg/condition/condition.go

Following are the components/functions for which tests can be added:
```
deleteJob
getScanResults
getScanSummary
createClusterscanReport
ensureCleanup
deletePod
isScanPresent
getClusterScanProfile
getClusterScanBenchmark
getDefaultClusterscan profile
validateClusterscanProfile
GetStatus
SetStatus
GetMessage
SetMessageIfBlank
```
A few more tests would be added/removed from the above list when the ticket will be worked upon.

**Comment by andypitcher** [comment]
I am closing this issue, to pursue this initiative in the following issue:

- https://github.com/rancher/cis-operator/issues/209
