### ISSUE TITLE
[v2.9] Update security scan profiles for cis chart

### ISSUE THREAD

**Issue by vardhaman22** [rancher/cis-operator#350]
issue to keep track of the changes being done in security scan for cis profiles.

**Comment by rishabhmsra** [comment]
RKE2 scan failures tracking issue - https://github.com/rancher/rancher/issues/46812
K3s scan failures tracking issue - https://github.com/rancher/rancher/issues/46663

**Comment by vivek-shilimkar** [comment]
Tested the CIS Benchmark chart on rancher v2.9-head.
Chart version installed - v6.2.0-rc2.

Tested on the normal and hardened k8s cluster v1.30 of RKE1, RKE2, and K3S versions. 

All scans with profile 1.8-permissive and 1.8-hardened passed. 

Hence closing the issue.
