### ISSUE TITLE
[Backport] [v2.8] Update security scan profiles for cis chart

### ISSUE THREAD

**Issue by vardhaman22** [rancher/cis-operator#351]
backport for issue: https://github.com/rancher/cis-operator/issues/350

**Comment by rishabhmsra** [comment]
RKE2 scan failures tracking issue - https://github.com/rancher/rancher/issues/46812
K3s scan failures tracking issue - https://github.com/rancher/rancher/issues/46663

**Comment by rishabhmsra** [comment]
Validated on rancher v2.8-head :

- Created v1.25 and v1.28, RKE1, KRE2 and k3s node driver as well as hardened clusters(1-cp, 1-e, 1-w)
- Created v1.26 RKE1, RKE2 and K3s node driver clusters.
- Created v1.26 RKE2 hardened cluster.
- Installed CIS chart 5.4.0-rc.2
- Ran v1.7 and v1.8 permissive and hardened profile scans on respective clusters and all scans passed, except on RKE1 hardened cluster 4.1.7 fails, which is expected.

**Comment by vivek-shilimkar** [comment]
Tested CIS chart v5.4.0-rc.1 on rancher v2.8-head with singlenode (RKE1, RKE2, K3S) k8s v1.25 and v1.28.
