### ISSUE TITLE
cis-operator workload is not deleted in local cluster on uninstalling cis v2 app

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#36]
**On master-head - commit id: `3950b8eabe`**

- Deploy a HA setup, on local cluster --> Install CIS v2 app via dashboard
- Delete both the operator and the crd once installed
- CIS CRDs are deleted. 
- Namespace is still available
- But the cis-operator workload is not deleted
- Error in cis-operator pod:
```
E0924 18:59:48.552639       1 reflector.go:178] github.com/rancher/lasso/pkg/cache/cache.go:118: Failed to list *v1.ClusterScan: the server could not find the requested resource (get clusterscans.meta.k8s.io)
E0924 19:00:32.623596       1 reflector.go:178] github.com/rancher/lasso/pkg/cache/cache.go:118: Failed to list *v1.ClusterScan: the server could not find the requested resource (get clusterscans.meta.k8s.io)
```
- User is however able to install the app again and clusterscans are run successfully on the cluster

**Note:**
cis-operator workload is deleted is a downstream user cluster in a HA setup.

**Comment by prachidamle** [comment]
I tested with HA setup running master-c983bb436bf76869891e7e2d5a6340f9618f01c6-head
I don't see cis-operator workload after I uninstalled the cis app. I see the namespace stay but no operator. 
I am able re-install the app back to local cluster and run clusterscans. 

Having namespace not cleared does not seem to be blocking any functionality.

**Comment by maggieliu** [comment]
@sowmyav27 Can you test again and see if operator is always left behind or just happened that one time?

**Comment by sowmyav27** [comment]
**On master-head - commit id: `4ac3a87`**

- Not able to reproduce this issue.
- CIS operator is deleted when the chart and CRDs are uninstalled.
- Closing this issue
