### ISSUE TITLE
CIS report should include additional fields  from kube-bench results

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#37]
CIS report should include additional fields like audit, audit_config, expected_result, actual_result fields from kube-bench results. This is needed to auto-generate the self-assessment guide.

**Comment by sowmyav27** [comment]
**On master-head - commit id: `c3bc230fe3`**

- Run a CIS v2 scan - Profile default on a custom RKE cluster (CIS benchmark app/chart should be dpeloyed)
- Download the report of the scan.
- The report contains additional fields: `audit, audit_config, test_info, commands, config_commands, actual_value, expected_result`
