### ISSUE TITLE
Downloaded CIS v2 report does not have the cis-1.5-profile or the benchmark value

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#39]
**On master-head - commit id: `c3bc230fe3`**

- On a custom RKE cluster - deploy CIS v2 charts
- Run scan - choose default profile
- Download the report from this scan.
- The report does not have the cis-1.5-profile or the benchmark value
- User will not know what benchmark/profile the scan has run

**Comment by rayandas** [comment]
Adding the benchmark value in the generated report might be redundant so we modified the generated scan report name in such a way that it includes the benchmark profile name as well everytime a scan runs.

**Comment by vivek-infracloud** [comment]
Tested the issue on rancher v2.7-head and CIS Benchmark chart version 3.0.1-rc6.

Downloaded report of the CIS scan. The name of report contains the CIS benchmark profile name.
Hence issue can be closed.
![Screenshot from 2023-01-27 17-27-20](https://user-images.githubusercontent.com/83208989/215081059-41558e97-f87d-43ad-b563-40cd82407205.png)
