### ISSUE TITLE
[CIS v2] Update RBAC to remove the aggregation label

### ISSUE THREAD

**Issue by maggieliu** [rancher/cis-operator#41]
* Update the charts to remove the aggregation label for the clusterRoles as these are not namespaced ones.
* Make sure the docs explains how the roles need to be assigned by cluster owner to users who need to have access to run CIS scan.

**Comment by ibrokethecloud** [comment]
Not sure if we need to considering this, but the ClusterRoles have namespaces assigned.

These are eventually ignored once they are applied.

[namespaced clusterrole](https://github.com/rancher/charts/blob/dev-v2.5-source/packages/rancher-cis-benchmark/charts/templates/cis-roles.yaml#L8)

**Comment by sowmyav27** [comment]
**On Verified on 2.5-head commit id: `1599dc142` - using cis charts - 1.0.100**
- Labels are available on the clusterroles
<img width="436" alt="Screen Shot 2020-10-22 at 3 30 13 PM" src="https://user-images.githubusercontent.com/26032343/96937167-681a8200-147c-11eb-847e-36e795504118.png">

**Verified on 2.5-head commit id: `1599dc142` - using cis charts - 1.0.200** with the fix

- `cis-edit` clusterrole is NOT available. 
- `aggregate-to-admin` labels are not available for cis-admin and cis-view clusterroles
<img width="432" alt="Screen Shot 2020-10-22 at 3 35 36 PM" src="https://user-images.githubusercontent.com/26032343/96937539-3524be00-147d-11eb-95f9-7f3ea056569f.png">
