### ISSUE TITLE
CIS v2 - Include non-scored tests in the scan reports along with the scored tests

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#42]
Currently with CIS 1.5, the ClusterScanReport contains only the scored testIds 
We should change this to also include the non-scored TestIds.

Also when we run the security-scan tool, we use the "--scored" option of  kube-bench cli that considers only the scored tests - but  we might have to run the tool without this flag to include all tests in the report

This work is needed when we consider CIS 1.6 benchmark

**Comment by mrajashree** [comment]
Available to test with https://github.com/mrajashree/charts/tree/cis16
Create new clusterRepo with repo https://github.com/mrajashree/charts and branch cis16, it has the new tags for security-scan and cis-operator images

The report will now include Unscored/Scored and Manual/Automated tests both. Prior to this, 1.5 reports only included Scored tests

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `f671292`**

- repo `https://github.com/mrajashree/charts` and branch `cis16`
- On a hardened cluster - 
<img width="1422" alt="Screen Shot 2020-11-23 at 10 11 14 PM" src="https://user-images.githubusercontent.com/26032343/100043071-a936e680-2dda-11eb-93d4-ca731485612e.png">

- Results are in par with doc mentioned [here](https://github.com/rancher/cis-operator/issues/46#issuecomment-731477337)
