### ISSUE TITLE
Scans are in error state when using custom benchmark version and custom scan profile

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#44]
**On 2.5.1**

- Create a custom benchmark version - clone it from `rke-cis-1.5-permissive`.
- Create a custom Scan profile using this benchmark version
- Create a cluster scan CR using this profile
- Scan will be in Error state
- Error: `time="2020-10-17T23:33:56Z" level=info msg="Running Summarizer" time="2020-10-17T23:33:56Z" level=debug msg="version_mapping: map[rke-1.18:rke-cis-1.5-permissive eks-1.0:eks-1.0 gke-1.0:gke-1.0 rke-1.13:rke-cis-1.4 rke-1.14:rke-cis-1.4 rke-1.15:rke-cis-1.5-permissive rke-1.16:rke-cis-1.5-permissive rke-1.17:rke-cis-1.5-permissive]" time="2020-10-17T23:33:56Z" level=error msg="error loading controls from file /etc/kube-bench/cfg/test-new/etcd.yaml: error reading file /etc/kube-bench/cfg/test-new/etcd.yaml: open /etc/kube-bench/cfg/test-new/etcd.yaml: no such file or directory" time="2020-10-17T23:33:56Z" level=error msg="error loading controls from file /etc/kube-bench/cfg/test-new/node.yaml: error reading file /etc/kube-bench/cfg/test-new/node.yaml: open /etc/kube-bench/cfg/test-new/node.yaml: no such file or directory" time="2020-10-17T23:33:56Z" level=error msg="error loading controls from file /etc/kube-bench/cfg/test-new/master.yaml: error reading file /etc/kube-bench/cfg/test-new/master.yaml: open /etc/kube-bench/cfg/test-new/master.yaml: no such file or directory" time="2020-10-17T23:33:56Z" level=debug msg="total groups loaded: 0" time="2020-10-17T23:33:56Z" level=debug msg="total controls loaded: 0" time="2020-10-17T23:33:56Z" level=info msg=summarize time="2020-10-17T23:33:56Z" level=debug msg="inputDir: /tmp/kb-summarizer/input/plugins/rancher-kube-bench/results" time="2020-10-17T23:33:56Z" level=debug msg="hostDir: ip-172-31-13-88" time="2020-10-17T23:33:56Z" level=info msg="found error file" time="2020-10-17T23:33:56Z" level=fatal msg="error summarizing: \nThe specified --targets \"etcd\" does not apply to the CIS Benchmark test-new \\n Valid targets []\n" error running kb-summarizer using override benchmark version`

**Expected:**
Scan should not error out.

**Comment by prachidamle** [comment]
I dont think this is related to custom scan or profile. This is an error I have seen intermittently happen possibly related to something not ready in the configuration of the scan pod.
It does not happen always and goes away with retries.

**Comment by SheilaghM** [comment]
Hasn't been seen after 2.5.1

**Comment by vivek-infracloud** [comment]
Tested a custom scan profile with rancher v2.7.0 with k8s v1.24.8 (RKE1)

Scans are passing. Hence closing the issue.
![Screenshot from 2022-12-15 13-25-47](https://user-images.githubusercontent.com/83208989/207804079-e202e3af-f331-43fe-9ff0-76e13d5dbf02.png)
