### ISSUE TITLE
Update CIS 1.5 in v2 CIS

### ISSUE THREAD

**Issue by mrajashree** [rancher/cis-operator#46]
- [x] Update the CIS 1.5 profile to include all scored=false tests 

- [x] Same for RKE profiles using CIS 1.5

**Comment by deniseschannon** [comment]
To Test:
1. Pre-upgrade: launch CIS scan chart
2. Run a RKE permissive and RKE hardened scan
3. Upgrade Rancher
4. Run a RKE permissive and RKE hardened scan
5. Upgrade CIS scan chart 
5. Run RKE permissive and RKE hardened scan

Confirm that the scan passes as expected on all 3 steps where we are running scans.

**Comment by mrajashree** [comment]
Available to test with https://github.com/mrajashree/charts/tree/cis16
Create new clusterRepo with repo https://github.com/mrajashree/charts and branch cis16, it has the new tags for security-scan and cis-operator images

On adding all missing tests in RKE 1.5 profiles from upstream CIS 1.5 profiles, some of them get counted as "Pass". Most others are "manual" with no audit scripts and generate "Warn" output. Ran them on both, hardened and non-hardened clusters.
I've created this to show all the new tests being added and the output they generate
https://docs.google.com/spreadsheets/d/15s8Ll1-Ih6N_vFdZSsQoEcyB7JbJ26C-LL50QU6QXv0/edit?usp=sharing

Ran hardened and permissive profiles on the hardened cluster, and ran only the permissive profile on the non-hardened cluster (since hardened profile will fail on it even with current profiles)

**Comment by sowmyav27** [comment]
**Upgrade use case from 2.5.3 to 2.5-head - commit id: `baf4867c`**

- On 2.5.3, deploy a custom cluster.
- Deploy CIS v2 app
- Run cluster scans - rke-permissive, rke-hardened, and cis 1.5 profiles
- Upgrade rancher to 2.5-head
- On the UI, the "warn" column is NOT shown for an admin user and a user who has cis-admin role can see the "warn" column but no "warn" count of tests. - Logged these  issues - https://github.com/rancher/dashboard/issues/2054 and  to track it
- Create a cluster scan, user is able to set the schedule scan and alerting on the UI. (doesnt work though as a cis v2 app upgrade is required). Logged [this](https://github.com/rancher/dashboard/issues/2052) issue to track it
- Upgrade cis v2 app.
