### ISSUE TITLE
CIS v2 permissive scan fails for flatcar linux cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#57]
**On 2.5-head - commit id: `9ee39b9`**

- Deploy a 5 node `flatcar linux 2605.6.0` cluster - 1 etcd, 1 control and 3 worker nodes.
- Install CIS v2 app
- Run rke permissive scan on the cluster.
- Scan fails

<img width="1407" alt="Screen Shot 2020-11-25 at 8 03 46 PM" src="https://user-images.githubusercontent.com/26032343/100296347-f4c3ce80-2f59-11eb-8552-bd3058356a0c.png">

Scan report:
[scan-report-scan-f5mhv.yaml.zip](https://github.com/rancher/cis-operator/files/5626618/scan-report-scan-f5mhv.yaml.zip)

**Comment by sowmyav27** [comment]
CIS 1.5 v1 permissive scan fails on a flatcar linux machine cluster

**Steps:**
on 2.5-head latest - commit id: `db350a63`

- Deploy a flatcar linux machine (flatcar-linux-stable-2605.6.0) cluster - 1 etcd/control and 3 worker nodes. Cluster.yml from [here](https://github.com/rancher/rke/issues/1744#issuecomment-597362929)
- Run CIS v1 permissive scan on the cluster.
- Some tests have failed:

<img width="1442" alt="Screen Shot 2020-12-01 at 6 10 35 PM" src="https://user-images.githubusercontent.com/26032343/100820400-f9c5c980-3402-11eb-82ae-f89a1e980a1c.png">

Report:
[cis-1606874237787512780.csv.zip](https://github.com/rancher/rancher/files/5626603/cis-1606874237787512780.csv.zip)


**Expected Result:**
All tests should pass



**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): on 2.5-head latest - commit id: `db350a63`**Steps to reproduce (least amount of steps as possible):**
on 2.5-head latest - commit id: `db350a63`

- Deploy a flatcar linux machine (flatcar-linux-stable-2605.6.0) cluster - 1 etcd/control and 3 worker nodes. Cluster.yml from [here](https://github.com/rancher/rke/issues/1744#issuecomment-597362929)
- Run CIS v1 permissive scan on the cluster.
- Some tests have failed:

<img width="1442" alt="Screen Shot 2020-12-01 at 6 10 35 PM" src="https://user-images.githubusercontent.com/26032343/100820400-f9c5c980-3402-11eb-82ae-f89a1e980a1c.png">

Report:
[cis-1606874237787512780.csv.zip](https://github.com/rancher/rancher/files/5626603/cis-1606874237787512780.csv.zip)


**Expected Result:**
All tests should pass


**Other details that may be helpful:**


**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): on 2.5-head latest - commit id: `db350a63`

**Comment by prachidamle** [comment]
There are 9 failures when CIS 1.5 permissive scan is run. We can fix 5 of them by adding the correct paths to certs and using a custom benchmark.
But 4 of the tests fail due to this issue:

When running CIS scan on a flatcar linux node, bunch of tests run stat -c command to check user:group of certain files and expects “root:root” to pass the test.
But what is seen is the groupname for root user is not found and stat command outputs “root:UNKNOWN” and the tests fail

**Comment by mitulshah-suse** [comment]
Issue is not reproducible.
On 2.7-head commit ID - 28a84c7
- Created flatcar linux RKE2 cluster - 1 cp 1 etcd 3 worker nodes
- Using flatcar AMI `Flatcar-stable-3374.2.1-hvm`

CIS 1.23 permissive scan passes without any errors.
![image](https://user-images.githubusercontent.com/109796209/209782973-d9940e8c-5d7b-4dc7-a521-3c99211b557d.png)
