### ISSUE TITLE
CIS v2 should be updated to support rke2 cluster scans

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#59]
The work is done under https://github.com/rancher/rke2/issues/1

**Comment by rancher-max** [comment]
#### Validated using `v1.18.12-rc1+rke2r2`

Steps were:
1. Create rke2 cluster with cis mode enabled (also checked one with cis mode not enabled, which has many more failures, as expected.)
2. Import cluster into rancher v2.5-head (`395b4fe`)
3. Navigate to cluster dashboard and enable CIS Benchmark app.
4. Run permissive scan
5. Run hardened scan

In the permissive scan, all scored tests pass and it shows as passing.
In the hardened scan, only one test fails, which is expected for control 5.1.5.
See attached results.

[hardenedreport.xlsx](https://github.com/rancher/cis-operator/files/5657320/hardenedreport.xlsx)
[permissivereport.xlsx](https://github.com/rancher/cis-operator/files/5657321/permissivereport.xlsx)

A couple of notes that I'd like confirmation on before closing this issue:
- @prachidamle When running a scan, I see 4 profiles available: the two for rke2 and cis-1.5-profile and cis-1.6-profile. Are these two expected to show up by default on any cluster? They will not pass (as expected) for rke2 clusters without a lot of manual intervention.
- @cjellick @davidnuzik @briandowns There are some mismatches between our self assessment and some of the checks in this scan. A few of the Not Scored incorrectly show as a failure (warn state), and a few of the Scored are marked not applicable even though they pass. These seem to make sense when comparing to upcoming state of rke2 (for example with different CNIs), but I'd like a final confirmation and to make sure these are known before signing off. 
  - 1.1.9 (Ensure that the Container Network Interface file permissions are set to 644 or more restrictive (Not Scored)) shows warn, self assessment is pass
  - 1.1.10 (Ensure that the Container Network Interface file ownership is set to root:root (Not Scored)) shows warn, self assessment is pass
  - 1.2.13 (Ensure that the admission control plugin SecurityContextDeny is set if PodSecurityPolicy is not used (Not Scored)) shows warn, self assessment is pass
  - 2.7 (Ensure that a unique Certificate Authority is used for etcd (Not Scored)) shows warn, self assessment is pass
  - 5.1.1 (Ensure that the cluster-admin role is only used where required (Not Scored)) shows warn, self assessment is pass
  - 2.1 (Ensure that the cert-file and key-file fields are set as appropriate (Scored)) shows not applicable, self assessment is pass
  - 2.2 (Ensure that the client-cert-auth field is set to true (Scored)) shows not applicable, self assessment is pass
  - 2.4 (Ensure that the peer-cert-file and peer-key-file fields are set as appropriate (Scored)) shows not applicable, self assessment is pass

**Comment by prachidamle** [comment]
> * @prachidamle When running a scan, I see 4 profiles available: the two for rke2 and cis-1.5-profile and cis-1.6-profile. Are these two expected to show up by default on any cluster? They will not pass (as expected) for rke2 clusters without a lot of manual intervention.

Yes  cis-1.5-profile and cis-1.6-profile will show up as well - they are the default generic profiles applicable to all clusters. It is ok if they do not pass.

**Comment by briandowns** [comment]
@rancher-max , in regards to the mismatches, the warns, the not applicable are in the context of the CIS doc but we call out that we do indeed pass them if it were to be marked as applicable by someone. The system marks not applicables as "warn". The reasons for them being marked that way are included in the self assessment guide. The one failure in "hardened" mode is expected and called out in documentation. There's a PR going in shortly that will remediate it. The gap really is between what the scan is doing and how we've written the self assessment guide. The self assessment guide is a copy of the CIS doc and customized for RKE2 specifically. CIS 1.6 makes for this process between documentation and scanning to be a lot simpler with the changes that were introduced.

**Comment by rancher-max** [comment]
Based on the comments I believe this is okay to be closed and is functioning correctly at this time
