### ISSUE TITLE
CIS v2: Add ability to configure new benchmark configs

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#6]
CIS V2 should support Customizable Benchmark Config - 

User can define a ConfigMap in clusterscanprofile CR  to override config data and the Operator should mount it to a directory. Startup script should check if the directory exists and use the test and config yamls from the mounted volume, instead of the defaults in the security-scan image.

**Comment by sowmyav27** [comment]
Blocked because of this issue - https://github.com/rancher/cis-operator/issues/69

**Comment by sowmyav27** [comment]
Closing this based on validation done here - https://github.com/rancher/cis-operator/issues/69
any other issues related will be tracked separately
