### ISSUE TITLE
Error while uninstalling CIS v2 app

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#61]
**On 2.5.3**

- Deploy CIS v2 app - 1.0.2
- Run a scan - rke profile permissive
- Scan runs successfully
- Uninstall CIS v2 app
- Errors when uninstalling `rancher-cis-benchmark`

```
helm uninstall --namespace=cis-operator-system rancher-cis-benchmark
Error: uninstallation completed with 1 error(s): unable to build kubernetes objects for delete: [unable to recognize "": no matches for kind "ClusterScanBenchmark" in version "cis.cattle.io/v1", unable to recognize "": no matches for kind "ClusterScanProfile" in version "cis.cattle.io/v1"]
```

Do not see the issue on 2.5-head - `db350a63bc` using CIS v2 app - 1.0.3

**Comment by prachidamle** [comment]
I do not see this error with 2.5-head

**Comment by sowmyav27** [comment]
Closing this one as it is not related to the cis operator but is tracked here - https://github.com/rancher/dashboard/issues/2037
