### ISSUE TITLE
Retention count of the scheduled scan is not maintained

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#64]
**On 2.5-head - commit id: `7e386eba`**

- Deploy CIS v2
- Create a scheduled scan.
- Give in retention count 1/2/4
- When scan runs, retention count see in the dropdown of how many reports are saved is always 3
- View in Yaml shows retention is correctly saved

**Comment by prachidamle** [comment]
@sowmyav27 I dont see this happening. I set the count to 2 and I can see only 2 reports in the dropdown always.

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `b2953cb`**

- Deployed a custom cluster
- installed CIS v2
- Deployed a schedule scan with retention-2
- Only 2 are seen retained.
- Original issue is NOT seen.

Closing it for now.
