### ISSUE TITLE
Access for users with cis-admin role

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#71]
**on 2.5-head - commit id - `395b4fe77 `**

- users with cis-admin roles should have access to default-clusterscanprofiles configmaps
- user with cis-admin should have access to "cis install configs"

Related issues:
- https://github.com/rancher/dashboard/issues/2020
- https://github.com/rancher/dashboard/issues/2021

**Comment by prachidamle** [comment]
@sowmyav27 I cannot reproduce this issue. 
- I added a  standard user to my cluster as cluster member.
- After logging in, this user cannot list rancher-cis-benchmark app.
- I created a new clusterrolebinding to grant cis-admin role
- now on refresh, the user can see  rancher-cis-benchmark app and also list scans and profiles

Is this reproducible only on a different UI tag?

**Comment by sowmyav27** [comment]
As per offline discussion with @prachidamle 

**Use case#1**
- On 2.5.3, deploy a cluster, custom, deploy CIS v2
- Run a scan - rke-permissive
- Upgrade to 2.5-head - commit id: `3463f5a8`
- Warn column does not have a count for a user with cis-admin role
<img width="1654" alt="Screen Shot 2020-12-10 at 11 54 08 AM" src="https://user-images.githubusercontent.com/26032343/101824070-8dbd2280-3ae0-11eb-81f4-5f0d26e2f5ec.png">


**Use case#2**
- On 2.5-head, user with cis-admin role, create a CIS scan CR, the default scan profile is not listed.
<img width="834" alt="Screen Shot 2020-12-10 at 9 16 32 AM" src="https://user-images.githubusercontent.com/26032343/101824194-b8a77680-3ae0-11eb-903b-8d3a9804b837.png">

**Comment by prachidamle** [comment]
@sowmyav27 I dont see usecase#1 happen - If you run a clusterscan on 2.5.3 it will not have any status.summary.warn count set.
So even after upgrade, the warn column will be empty for that clusterscan object.

After upgrade, if user creates a new clusterscan then there will be a value filled in for "warn" column for new scans.

<img width="1517" alt="Screen Shot 2020-12-11 at 6 54 03 PM" src="https://user-images.githubusercontent.com/1470602/101970957-8716d400-3be2-11eb-9c75-04d6b1bc6be8.png">

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `e2295c6 ` using cis v2 app v1.0.3**

```
cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.3-rc4
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.2-rc4
```

- As an admin deploy CIS v2, create a scan CR
- Create a user - user-1 with cis-admin roles using add the user as a cluster member of the cluster
- Login as user-1 --> Dashboard --> CIS benchmarks
- Create Scan CR
- Cluster member with CIS admin role is able to list clusterscan profiles and create scan CRs
