### ISSUE TITLE
Scheduled scan runs after an edit and changing the scan to a one time scan

### ISSUE THREAD

**Issue by sowmyav27** [rancher/cis-operator#75]
**On 2.5-head - commit id: `baf4867` with latest cis v2 charts: `rancher-cis-benchmark:1.0.300`**

- Create a scan CR.
- Enable Scheduled scan . Cron - * * * * * and Retention:3 (any), profile: Any
- Scan runs and completes. The next scan is scheduled to happen.
- Edit the scan CR and change it to "One time" Scan run and save changes made
- The next scheduled scan still runs, and then the scheduled scan is "disabled" no more scheduled scan runs. 

**Questions:**
- Is this behavior expected?
- When a scheduled scan is edited and made into a one time scan run, do we need to run the next scheduled scan?

**Comment by prachidamle** [comment]
This is as expected, the scan object has been scheduled earlier and queued to run after a certain time instant, at which point kubernetes controller will invoke the run. After this run however no next run will get scheduled since the scan config is changed.

**Comment by maggieliu** [comment]
@sowmyav27 can you close this if you are fine with Prachi's explanantion?

**Comment by sowmyav27** [comment]
Closing the issue based on [comments](https://github.com/rancher/cis-operator/issues/75#issuecomment-744618609)
