### ISSUE TITLE
Drop vendor dependencies from cis-operator

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#78]
Drop vendor dir in cis-operator and bump the go version

**Comment by SheilaghM** [comment]
Can release with  https://github.com/rancher/cis-operator/issues/81

**Comment by prachidamle** [comment]
This fix is only bumping go version and dropping vendor from cis-operator. Only tests needed is functional sanity testing, no new functionality added.

**Comment by kravciak** [comment]
I tested on v2.5-head (4115dee) with dev-2.5 chart, it deployed successfully.
Tested on custom cluster (3 ubuntu aws nodes created by jenkins job).
Test took few minutes to start, probably because of requeuing.

Installed apps:
- rancher-cis-benchmark:1.0.400-rc01
- rancher-cis-benchmark-crd:1.0.400-rc01

Created deployment:
- rancher/cis-operator:v1.0.4-rc1


```
~ kubectl logs -n cis-operator-system cis-operator-6bf6d4949f-pxcqt
time="2021-04-07T11:04:22Z" level=info msg="Starting CIS-Operator"
time="2021-04-07T11:04:22Z" level=info msg="ClusterProvider detected rke"
time="2021-04-07T11:04:22Z" level=info msg="KubernetesVersion detected v1.20.5"
time="2021-04-07T11:04:23Z" level=info msg="Starting cis.cattle.io/v1, Kind=ClusterScan controller"
time="2021-04-07T11:04:23Z" level=info msg="Starting /v1, Kind=ConfigMap controller"
time="2021-04-07T11:04:23Z" level=info msg="Starting /v1, Kind=Service controller"
time="2021-04-07T11:04:23Z" level=info msg="Starting /v1, Kind=Pod controller"
time="2021-04-07T11:04:23Z" level=info msg="Starting batch/v1, Kind=Job controller"
time="2021-04-07T11:11:58Z" level=info msg="Launching a new on demand Job for scan scan-tlc7l to run cis using profile rke-profile-permissive-1.6"
time="2021-04-07T11:11:58Z" level=error msg="error syncing 'scan-tlc7l': handler cis-operator: Retrying ClusterScan scan-tlc7l since got error: A rancher-cis-benchmark scan runner job is already running , requeuing"
time="2021-04-07T11:12:30Z" level=info msg="Marking ClusterScanConditionRunCompleted for scan: scan-tlc7l"
time="2021-04-07T11:12:30Z" level=info msg="Marking ClusterScanConditionComplete for scan: scan-tlc7l"
time="2021-04-07T11:12:30Z" level=info msg="Marking ClusterScanConditionAlerted for scan: scan-tlc7l"
```

**Comment by kravciak** [comment]
Can you confirm the error is ok and can be ignored?
In that case I can close this card, everything else worked fine.
```
error syncing 'scan-tlc7l': handler cis-operator: Retrying ClusterScan scan-tlc7l since got error:
A rancher-cis-benchmark scan runner job is already running , requeuing
```

**Comment by kravciak** [comment]
> Can you confirm the error is ok and can be ignored?

Yes this is ok, it is not an issue. It is printed since another scan is already running, so this scan has to retry.

Will test on master-head after https://github.com/rancher/rancher/issues/31964 is fixed before closing

**Comment by kravciak** [comment]
Blocked on https://github.com/rancher/rancher/issues/31964

**Comment by sowmyav27** [comment]
Tracking master validations here - https://github.com/rancher/cis-operator/issues/91. closing this issue.
