### ISSUE TITLE
CIS v2: Support cluster scan profiles and provide ability to create custom profiles to skip tests

### ISSUE THREAD

**Issue by prachidamle** [rancher/cis-operator#8]
- As part of CIS v2, 
- Support default cluster scan profiles for current rke permissive and hardened benchmarks
- Support custom scan profiles where user can define the tests to skip.

**Comment by prachidamle** [comment]
This has been fixed using the cis-operator and ClusterScanProfile CRD. Seems duplicate of https://github.com/rancher/cis-operator/issues/18

**Comment by sowmyav27** [comment]
**On master-head - commit id: `76c26fb0f9`**

- Deploy cis-operator from repo - `https://github.com/prachidamle/charts.git` branch: `cis-v2-chart`. chart Images:
```
  cisoperator:
    repository: rancher/cis-operator
    tag: v0.0.4
  securityScan:
    repository: prachidamle/security-scan
    tag: v0.1.20
```
- Create a custom scan profile -
```
apiVersion: cis.cattle.io/v1
kind: ClusterScanProfile
metadata:
  annotations:
    meta.helm.sh/release-name: clusterscan-operator
    meta.helm.sh/release-namespace: cis-operator-system
  creationTimestamp: "2020-09-07T18:52:15Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: custom-gke
  resourceVersion: "4714"
  selfLink: /apis/cis.cattle.io/v1/clusterscanprofiles/custom-gke
  uid: fbf3c349-e567-4685-b2c0-d8d4639607a5
spec:
  benchmarkVersion: gke-1.0
  skipTests:
  - 4.1.10
  - 4.1.9
  - 4.1.4
```
- Run scan by creating a clusterscan CR using this scan profile.
- Summary of scan run 
```
summary:
    fail: 41
    notApplicable: 0
    pass: 4
    skip: 3
    total: 48
```
- User is able to mention tests to skip during a scan by creating customs can profiles.
- Default scan profiles available include  rke permissive and hardened benchmarks.
<img width="1443" alt="Screen Shot 2020-09-07 at 11 54 39 AM" src="https://user-images.githubusercontent.com/26032343/92412497-ef947780-f100-11ea-97e2-5d73ca9bc113.png">
