### ISSUE TITLE
Starting batch/v1, Kind=Job controller never progresses

### ISSUE THREAD

**Issue by benhosmer** [rancher/cis-operator#90]
I installed the crds already, see https://github.com/rancher/cis-operator/pull/89

I can't get past:
```
./cis-operator-amd64 
INFO[0000] Starting CIS-Operator                        
INFO[0000] ClusterProvider detected rke2                
INFO[0000] KubernetesVersion detected v1.19.9+rke2r1    
INFO[0000] Starting cis.cattle.io/v1, Kind=ClusterScan controller 
INFO[0000] Starting /v1, Kind=Service controller        
INFO[0000] Starting /v1, Kind=Pod controller            
INFO[0000] Starting /v1, Kind=ConfigMap controller      
INFO[0000] Starting batch/v1, Kind=Job controller  
```

**Comment by prachidamle** [comment]
@benhosmer your cis-operator pod has started successfully, now you need to create a ClusterScan custrom resource by setting appropriate clusterscanprofile and the operator will pick it up and run that profile.

For example create a CR using kubectl like this:
```
---
apiVersion: cis.cattle.io/v1
kind: ClusterScanProfile
metadata:
  name: rke-profile-permissive
spec:
  benchmarkVersion: rke-cis-1.5-permissive
---
apiVersion: cis.cattle.io/v1
kind: ClusterScan
metadata:
  name: rke-cis-perm
spec:
  scanProfileName: "rke-profile-permissive"
```

Refer Docs that can clarify: https://rancher.com/docs/rancher/v2.x/en/cis-scans/v2.5/#running-a-scan

**Comment by dramich** [comment]
@benhosmer Closing as it looks like your question was answered. If you need more assistance feel free to open a new issue.
